flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 5%
      - type: patch
        target: 80%

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto

individual_components:
  - component_id: api
    paths:
      - api/**
  - component_id: app
    paths:
      - app/**
  - component_id: sdk
    paths:
      - sdk/**
  - component_id: components
    paths:
      - packages/components/**
  - component_id: composables
    paths:
      - packages/composables/**
  - component_id: env
    paths:
      - packages/env/**
  - component_id: errors
    paths:
      - packages/errors/**
  - component_id: extensions
    paths:
      - packages/extensions/**
  - component_id: extensions-registry
    paths:
      - packages/extensions-registry/**
  - component_id: extensions-sdk
    paths:
      - packages/extensions-sdk/**
  - component_id: format-title
    paths:
      - packages/format-title/**
  - component_id: memory
    paths:
      - packages/memory/**
  - component_id: pressure
    paths:
      - packages/pressure/**
  - component_id: random
    paths:
      - packages/random/**
  - component_id: release-notes-generator
    paths:
      - packages/release-notes-generator/**
  - component_id: schema-builder
    paths:
      - packages/schema-builder/**
  - component_id: storage
    paths:
      - packages/storage/**
  - component_id: storage-driver-azure
    paths:
      - packages/storage-driver-azure/**
  - component_id: storage-driver-cloudinary
    paths:
      - packages/storage-driver-cloudinary/**
  - component_id: storage-driver-gcs
    paths:
      - packages/storage-driver-gcs/**
  - component_id: storage-driver-local
    paths:
      - packages/storage-driver-local/**
  - component_id: storage-driver-s3
    paths:
      - packages/storage-driver-s3/**
  - component_id: storage-driver-supabase
    paths:
      - packages/storage-driver-supabase/**
  - component_id: update-check
    paths:
      - packages/update-check/**
  - component_id: utils
    paths:
      - packages/utils/**
  - component_id: validation
    paths:
      - packages/validation/**

comment:
  layout: 'header, diff, components'
