packages:
  - directus
  - app
  - api
  - sdk
  - packages/*
  - tests/*

catalog:
  '@authenio/samlify-node-xmllint': 2.0.0
  '@aws-sdk/client-s3': 3.918.0
  '@aws-sdk/client-sesv2': 3.918.0
  '@aws-sdk/lib-storage': 3.918.0
  '@azure/storage-blob': 12.29.1
  '@changesets/cli': 2.29.7
  '@changesets/get-github-info': 0.6.0
  '@changesets/types': 6.1.0
  '@directus/schema-builder': workspace:*
  '@directus/tsconfig': 3.0.0
  '@directus/types': workspace:*
  '@editorjs/attaches': 1.3.2
  '@editorjs/checklist': 1.6.0
  '@editorjs/code': 2.9.3
  '@editorjs/delimiter': 1.4.2
  '@editorjs/editorjs': 2.31.0
  '@editorjs/embed': 2.7.6
  '@editorjs/header': 2.8.8
  '@editorjs/image': 2.10.3
  '@editorjs/inline-code': 1.5.2
  '@editorjs/nested-list': 1.4.3
  '@editorjs/paragraph': 2.11.7
  '@editorjs/quote': 2.7.6
  '@editorjs/raw': 2.5.1
  '@editorjs/table': 2.4.5
  '@editorjs/underline': 1.2.1
  '@eslint/js': 9.38.0
  '@fortawesome/fontawesome-svg-core': 6.7.2
  '@fortawesome/free-brands-svg-icons': 6.7.2
  '@fullcalendar/core': 6.1.19
  '@fullcalendar/daygrid': 6.1.19
  '@fullcalendar/interaction': 6.1.19
  '@fullcalendar/list': 6.1.19
  '@fullcalendar/timegrid': 6.1.19
  '@godaddy/terminus': 4.12.1
  '@google-cloud/storage': 7.17.2
  '@histoire/plugin-vue': 0.17.17
  '@joeattardi/emoji-button': 4.6.4
  '@json2csv/plainjs': 7.0.6
  '@keyv/redis': 3.0.1
  '@mapbox/mapbox-gl-draw': 1.5.0
  '@mapbox/mapbox-gl-draw-static-mode': 1.0.1
  '@mapbox/mapbox-gl-geocoder': 5.1.2
  '@modelcontextprotocol/sdk': 1.20.2
  '@ngneat/falso': 8.0.2
  '@npm/types': 2.1.0
  '@pinia/testing': 1.0.2
  '@pnpm/logger': 1001.0.1
  '@pnpm/workspace.find-packages': 1000.0.43
  '@pnpm/workspace.pkgs-graph': 1000.0.25
  '@popperjs/core': 2.11.8
  '@rollup/plugin-alias': 5.1.1
  '@rollup/plugin-commonjs': 28.0.9
  '@rollup/plugin-json': 6.1.0
  '@rollup/plugin-node-resolve': 16.0.3
  '@rollup/plugin-replace': 6.0.2
  '@rollup/plugin-terser': 0.4.4
  '@rollup/plugin-virtual': 3.0.2
  '@rollup/plugin-yaml': 4.1.2
  '@shopify/semaphore': 3.1.0
  '@sinclair/typebox': 0.34.41
  '@sindresorhus/slugify': 2.2.1
  '@smithy/node-http-handler': 4.4.3
  '@supabase/storage-js': 2.76.1
  '@tinymce/tinymce-vue': 6.3.0
  '@turf/meta': 7.2.0
  '@tus/server': 2.3.0
  '@tus/utils': 0.6.0
  '@types/async': 3.2.25
  '@types/base-64': 1.0.2
  '@types/busboy': 1.5.4
  '@types/bytes': 3.1.5
  '@types/chroma-js': 3.1.2
  '@types/codemirror': 5.60.16
  '@types/content-disposition': 0.5.9
  '@types/cookie-parser': 1.4.10
  '@types/cors': 2.8.19
  '@types/deep-diff': 1.0.5
  '@types/destroy': 1.0.3
  '@types/diacritics': 1.3.3
  '@types/diff': 7.0.1
  '@types/encodeurl': 1.0.3
  '@types/express': 4.17.21
  '@types/express-serve-static-core': 4.19.6
  '@types/file-saver': 2.0.7
  '@types/fs-extra': 11.0.4
  '@types/geojson': 7946.0.16
  '@types/glob-to-regexp': 0.4.4
  '@types/inquirer': 9.0.9
  '@types/js-yaml': 4.0.9
  '@types/json2csv': 5.0.7
  '@types/jsonwebtoken': 9.0.10
  '@types/ldapjs': 2.2.5
  '@types/lodash': 4.17.20
  '@types/lodash-es': 4.17.12
  '@types/mapbox__mapbox-gl-draw': 1.4.9
  '@types/mapbox__mapbox-gl-geocoder': 5.1.0
  '@types/mime-types': 3.0.1
  '@types/ms': 2.1.0
  '@types/node': 22.13.14
  '@types/cron': 3.0.11
  '@types/nodemailer': 7.0.3
  '@types/object-hash': 3.0.6
  '@types/papaparse': 5.3.16
  '@types/proxy-addr': 2.0.3
  '@types/qrcode': 1.5.6
  '@types/qs': 6.14.0
  '@types/sanitize-html': 2.16.0
  '@types/semver': 7.7.1
  '@types/stream-json': 1.7.8
  '@types/tmp': 0.2.6
  '@types/wellknown': 0.5.8
  '@types/ws': 8.18.1
  '@unhead/addons': 1.11.20
  '@unhead/vue': 1.11.20
  '@vitejs/plugin-vue': 6.0.1
  '@vitest/coverage-v8': 3.2.4
  '@vue/test-utils': 2.4.6
  '@vueuse/core': 14.0.0
  '@vueuse/integrations': 14.0.0
  '@vueuse/router': 14.0.0
  apexcharts: 4.7.0
  argon2: 0.44.0
  async: 3.2.6
  async-mutex: 0.5.0
  axios: 1.12.2
  axios-cache-interceptor: 1.8.3
  base-64: 1.0.0
  boxen: 8.0.1
  busboy: 1.6.0
  bytes: 3.1.2
  camelcase: 8.0.0
  caret-pos: 2.0.0
  chalk: 5.6.2
  chokidar: 4.0.3
  chroma-js: 3.1.2
  codemirror: 5.65.18
  color: 5.0.2
  commander: 14.0.2
  content-disposition: 0.5.4
  cookie: 1.0.2
  cookie-parser: 1.4.7
  copyfiles: 2.4.1
  cors: 2.8.5
  cron: 4.3.3
  cropperjs: 1.6.2
  date-fns: 4.1.0
  decamelize: 6.0.1
  deep-diff: 1.0.2
  destroy: 1.2.0
  diacritics: 1.3.0
  diff: 7.0.0
  dompurify: 3.3.0
  dotenv: 17.2.3
  editorjs-toggle-block: 0.3.16
  encodeurl: 2.0.0
  esbuild: 0.25.11
  esbuild-plugin-replace: 1.4.0
  escape-string-regexp: 5.0.0
  eslint: 9.38.0
  eslint-config-prettier: 10.1.8
  eslint-plugin-vue: 10.5.1
  eventemitter2: 6.4.9
  execa: 9.6.0
  exif-reader: 2.0.2
  express: 4.21.2
  file-saver: 2.0.5
  find-cache-directory: 6.0.0
  flat: 6.0.1
  flatpickr: 4.6.13
  focus-trap: 7.6.6
  form-data: 4.0.4
  fs-extra: 11.3.2
  geojson: 0.5.0
  get-port: 7.1.0
  glob-to-regexp: 0.4.1
  globals: 16.4.0
  graphql: 16.11.0
  graphql-compose: 9.1.0
  graphql-ws: 6.0.6
  happy-dom: 20.0.10
  helmet: 8.1.0
  histoire: 0.17.17
  html-entities: 2.6.0
  icc: 3.0.0
  inquirer: 12.10.0
  ioredis: 5.8.2
  ip-matching: 2.1.2
  isolated-vm: 5.0.3
  joi: 18.0.1
  js-yaml: 4.1.0
  js2xmlparser: 5.0.0
  json-to-graphql-query: 2.3.0
  json2csv: 5.0.7
  jsonlint-mod: 1.7.6
  jsonwebtoken: 9.0.2
  keyv: 5.5.3
  knex: 3.1.0
  knex-mock-client: 3.0.2
  ky: 1.13.0
  ldapjs: 2.3.3
  liquidjs: 10.24.0
  lodash: 4.17.21
  lodash-es: 4.17.21
  log-symbols: 7.0.1
  lru-cache: 11.2.2
  mapbox-gl: 1.13.3
  maplibre-gl: 1.15.3
  marked: 16.4.1
  micromustache: 8.0.3
  mime: 4.1.0
  mime-types: 3.0.1
  minimatch: 10.1.1
  mitt: 3.0.1
  mnemonist: 0.40.3
  ms: 2.1.3
  mysql2: 3.15.3
  nanoid: 5.1.6
  node-machine-id: 1.1.12
  nodemailer: 7.0.10
  nodemailer-mailgun-transport: 2.1.5
  npm-watch: 0.13.0
  object-hash: 3.0.0
  ofetch: 1.5.0
  openapi3-ts: 4.5.0
  openid-client: 5.7.1
  ora: 8.2.0
  oracledb: 6.10.0
  otplib: 12.0.1
  p-limit: 7.2.0
  p-queue: 8.1.0
  papaparse: 5.5.3
  pg: 8.16.3
  pinia: 2.3.1
  pino: 9.7.0
  pino-http: 10.5.0
  pino-http-print: 3.1.0
  pino-pretty: 13.1.2
  pm2: 6.0.13
  postcss-html: 1.8.0
  prettier: 3.6.2
  pretty-ms: 9.3.0
  prom-client: 15.1.3
  proxy-addr: 2.0.7
  qrcode: 1.5.4
  qs: 6.14.0
  rate-limiter-flexible: 7.2.0
  rimraf: 6.0.1
  rolldown: 1.0.0-beta.31
  rollup: 4.52.5
  rollup-plugin-esbuild: 6.2.1
  rollup-plugin-node-externals: 8.1.1
  rollup-plugin-styler: 2.0.0
  samlify: 2.10.1
  sanitize-html: 2.17.0
  sass-embedded: 1.93.2
  semver: 7.7.3
  sharp: 0.34.4
  snappy: 7.3.3
  sqlite3: 5.1.7
  stream-json: 1.9.1
  string-width: 7.2.0
  strip-ansi: 7.1.2
  stylelint: 16.25.0
  stylelint-config-standard: 39.0.1
  stylelint-config-standard-scss: 15.0.1
  stylelint-config-standard-vue: 1.0.0
  stylelint-use-logical: 2.1.2
  swagger-cli: 4.0.4
  swagger-ui-watcher: 2.1.14
  tar: 7.5.1
  tedious: 18.6.1
  tinymce: 6.8.6
  tmp: 0.2.5
  tsdown: 0.15.11
  tsx: 4.20.6
  tus-js-client: 4.3.1
  typescript: 5.9.3
  typescript-eslint: 8.46.2
  undici: 7.16.0
  unplugin-yaml: 3.0.7
  update-check: 1.5.4
  uuid: 11.1.0
  vite: 7.1.12
  vite-plugin-dts: 4.5.4
  vite-plugin-vue-devtools: 7.7.2
  vitest: 3.2.4
  vue: 3.5.22
  vue-i18n: 11.1.12
  vue-router: 4.6.3
  vue-tsc: 3.1.2
  vue-virtual-scroller: 2.0.0-beta.8
  vuedraggable: 4.1.0
  wellknown: 0.5.0
  ws: 8.18.3
  zod: 4.1.12
  zod-validation-error: 4.0.2

catalogMode: strict

onlyBuiltDependencies:
  - '@fortawesome/fontawesome-common-types'
  - '@fortawesome/fontawesome-svg-core'
  - '@fortawesome/free-regular-svg-icons'
  - '@fortawesome/free-solid-svg-icons'
  - '@parcel/watcher'
  - argon2
  - esbuild
  - isolated-vm
  - oracledb
  - sharp
  - sqlite3
  - vue-demi
