packages:
  - directus
  - app
  - api
  - docs
  - sdk
  - packages/*
  - tests/*
catalog:
  "@authenio/samlify-node-xmllint": 2.0.0
  "@aws-sdk/client-s3": 3.758.0
  "@aws-sdk/client-ses": 3.758.0
  "@aws-sdk/lib-storage": 3.758.0
  "@azure/storage-blob": 12.26.0
  "@changesets/cli": 2.28.1
  "@changesets/get-github-info": 0.6.0
  "@changesets/types": 6.1.0
  "@directus/tsconfig": 3.0.0
  "@editorjs/attaches": 1.3.0
  "@editorjs/checklist": 1.6.0
  "@editorjs/code": 2.9.0
  "@editorjs/delimiter": 1.4.2
  "@editorjs/editorjs": 2.29.1
  "@editorjs/embed": 2.7.4
  "@editorjs/header": 2.8.1
  "@editorjs/image": 2.9.3
  "@editorjs/inline-code": 1.5.1
  "@editorjs/nested-list": 1.4.3
  "@editorjs/paragraph": 2.11.5
  "@editorjs/quote": 2.7.2
  "@editorjs/raw": 2.5.0
  "@editorjs/table": 2.3.0
  "@editorjs/underline": 1.1.0
  "@eslint/js": 9.21.0
  "@fortawesome/fontawesome-svg-core": 6.7.2
  "@fortawesome/free-brands-svg-icons": 6.7.2
  "@fullcalendar/core": 6.1.15
  "@fullcalendar/daygrid": 6.1.15
  "@fullcalendar/interaction": 6.1.15
  "@fullcalendar/list": 6.1.15
  "@fullcalendar/timegrid": 6.1.15
  "@godaddy/terminus": 4.12.1
  "@google-cloud/storage": 7.15.2
  "@histoire/plugin-vue": 0.17.17
  "@joeattardi/emoji-button": 4.6.4
  "@json2csv/plainjs": 7.0.6
  "@keyv/redis": 3.0.1
  "@mapbox/mapbox-gl-draw": 1.5.0
  "@mapbox/mapbox-gl-draw-static-mode": 1.0.1
  "@mapbox/mapbox-gl-geocoder": 5.0.3
  "@ngneat/falso": 7.3.0
  "@npm/types": 2.0.0
  "@pinia/testing": 1.0.0
  "@pnpm/find-workspace-dir": 900.0.1
  "@pnpm/workspace.find-packages": 900.0.5
  "@pnpm/workspace.pkgs-graph": 900.0.3
  "@popperjs/core": 2.11.8
  "@rollup/plugin-alias": 5.1.1
  "@rollup/plugin-commonjs": 25.0.8
  "@rollup/plugin-json": 6.1.0
  "@rollup/plugin-node-resolve": 15.3.1
  "@rollup/plugin-replace": 5.0.7
  "@rollup/plugin-terser": 0.4.4
  "@rollup/plugin-virtual": 3.0.2
  "@rollup/plugin-yaml": 4.1.2
  "@shopify/semaphore": 3.1.0
  "@sinclair/typebox": 0.34.28
  "@sindresorhus/slugify": 2.2.1
  "@smithy/node-http-handler": 4.0.3
  "@supabase/storage-js": 2.7.1
  "@tinymce/tinymce-vue": 6.1.0
  "@turf/meta": 7.2.0
  "@tus/server": 1.10.2
  "@tus/utils": 0.5.1
  "@types/async": 3.2.24
  "@types/base-64": 1.0.2
  "@types/busboy": 1.5.4
  "@types/bytes": 3.1.5
  "@types/chroma-js": 3.1.1
  "@types/codemirror": 5.60.15
  "@types/content-disposition": 0.5.8
  "@types/cookie-parser": 1.4.8
  "@types/cors": 2.8.17
  "@types/deep-diff": 1.0.5
  "@types/destroy": 1.0.3
  "@types/diacritics": 1.3.3
  "@types/diff": 7.0.1
  "@types/encodeurl": 1.0.2
  "@types/express": 4.17.21
  "@types/express-serve-static-core": 4.19.6
  "@types/file-saver": 2.0.7
  "@types/fs-extra": 11.0.4
  "@types/geojson": 7946.0.16
  "@types/glob-to-regexp": 0.4.4
  "@types/inquirer": 9.0.7
  "@types/js-yaml": 4.0.9
  "@types/json2csv": 5.0.7
  "@types/jsonwebtoken": 9.0.9
  "@types/ldapjs": 2.2.5
  "@types/lodash": 4.17.16
  "@types/lodash-es": 4.17.12
  "@types/mapbox__mapbox-gl-draw": 1.4.8
  "@types/mapbox__mapbox-gl-geocoder": 5.0.0
  "@types/mime-types": 2.1.4
  "@types/ms": 2.1.0
  "@types/node": 22.13.8
  "@types/node-schedule": 2.1.7
  "@types/nodemailer": 6.4.17
  "@types/object-hash": 3.0.6
  "@types/papaparse": 5.3.15
  "@types/proxy-addr": 2.0.3
  "@types/qrcode": 1.5.5
  "@types/qs": 6.9.18
  "@types/sanitize-html": 2.13.0
  "@types/seedrandom": 3.0.8
  "@types/semver": 7.5.8
  "@types/stream-json": 1.7.8
  "@types/supertest": 6.0.2
  "@types/tmp": 0.2.6
  "@types/wellknown": 0.5.8
  "@types/ws": 8.5.14
  "@unhead/addons": 1.11.20
  "@unhead/vue": 1.11.20
  "@vitest/coverage-v8": 2.1.9
  "@vue/test-utils": 2.4.6
  "@vueuse/core": 12.7.0
  "@vueuse/integrations": 12.7.0
  "@vueuse/router": 12.7.0
  apexcharts: 4.5.0
  argon2: 0.41.1
  async: 3.2.6
  async-mutex: 0.5.0
  autocannon: 8.0.0
  axios: 1.8.4
  axios-cache-interceptor: 1.6.2
  base-64: 1.0.0
  boxen: 8.0.1
  busboy: 1.6.0
  bytes: 3.1.2
  camelcase: 8.0.0
  caret-pos: 2.0.0
  chalk: 5.4.1
  chokidar: 3.6.0
  chroma-js: 3.1.2
  codemirror: 5.65.18
  color: 5.0.0
  content-disposition: 0.5.4
  cookie: 1.0.2
  cookie-parser: 1.4.7
  copyfiles: 2.4.1
  cors: 2.8.5
  cron-parser: 4.9.0
  cropperjs: 1.6.2
  date-fns: 4.1.0
  decamelize: 6.0.0
  deep-diff: 1.0.2
  destroy: 1.2.0
  diacritics: 1.3.0
  diff: 7.0.0
  dompurify: 3.2.4
  dotenv: 16.4.7
  editorjs-toggle-block: 0.3.16
  encodeurl: 2.0.0
  esbuild: 0.25.0
  esbuild-plugin-replace: 1.4.0
  esbuild-yaml: 2.0.0
  escape-string-regexp: 5.0.0
  eslint: 9.21.0
  eslint-config-prettier: 9.1.0
  eslint-plugin-vue: 9.32.0
  eventemitter2: 6.4.9
  exif-reader: 2.0.2
  express: 4.21.2
  file-saver: 2.0.5
  find-cache-dir: 5.0.0
  flat: 6.0.1
  flatpickr: 4.6.13
  form-data: 4.0.2
  fs-extra: 11.3.0
  geojson: 0.5.0
  get-port: 7.1.0
  glob-to-regexp: 0.4.1
  globals: 15.15.0
  globby: 14.1.0
  graphql: 16.10.0
  graphql-compose: 9.1.0
  graphql-ws: 5.16.2
  happy-dom: 17.1.8
  helmet: 8.0.0
  histoire: 0.17.17
  html-entities: 2.5.2
  icc: 3.0.0
  inquirer: 12.4.2
  ioredis: 5.5.0
  ip-matching: 2.1.2
  isolated-vm: 5.0.3
  joi: 17.13.3
  js-yaml: 4.1.0
  js2xmlparser: 5.0.0
  json-to-graphql-query: 2.3.0
  json2csv: 5.0.7
  jsonlint-mod: 1.7.6
  jsonwebtoken: 9.0.2
  keyv: 5.3.0
  knex: 3.1.0
  knex-mock-client: 3.0.2
  ky: 1.7.5
  ldapjs: 2.3.3
  liquidjs: 10.21.0
  listr2: 8.2.5
  lodash: 4.17.21
  lodash-es: 4.17.21
  log-symbols: 7.0.0
  lru-cache: 11.0.2
  mapbox-gl: 1.13.3
  maplibre-gl: 1.15.3
  markdown-it-for-inline: 2.0.1
  marked: 15.0.7
  micromustache: 8.0.3
  mime: 4.0.6
  mime-types: 2.1.35
  minimatch: 10.0.1
  mitt: 3.0.1
  mnemonist: 0.40.3
  ms: 2.1.3
  mysql2: 3.12.0
  nanoid: 5.1.2
  node-fetch: 3.3.2
  node-machine-id: 1.1.12
  node-schedule: 2.1.1
  nodemailer: 6.10.0
  nodemailer-mailgun-transport: 2.1.5
  npm-watch: 0.13.0
  object-hash: 3.0.0
  ofetch: 1.4.1
  openapi3-ts: 4.4.0
  openid-client: 5.7.1
  oracledb: 6.8.0
  otplib: 12.0.1
  p-limit: 6.2.0
  p-queue: 8.1.0
  papaparse: 5.5.2
  pg: 8.13.3
  pinia: 2.3.1
  pino: 9.6.0
  pino-http: 10.4.0
  pino-http-print: 3.1.0
  pino-pretty: 13.0.0
  pm2: 5.4.3
  postcss-html: 1.8.0
  prettier: 3.1.0
  pretty-ms: 9.2.0
  prom-client: 15.1.3
  proxy-addr: 2.0.7
  qrcode: 1.5.4
  qs: 6.14.0
  rate-limiter-flexible: 5.0.5
  rimraf: 6.0.1
  rollup: 4.34.9
  rollup-plugin-esbuild: 6.2.1
  rollup-plugin-node-externals: 8.0.0
  rollup-plugin-styler: 2.0.0
  samlify: 2.10.0
  sanitize-html: 2.14.0
  sass-embedded: 1.85.1
  seedrandom: 3.0.5
  semver: 7.7.1
  sharp: 0.33.5
  snappy: 7.2.2
  spellchecker-cli: 7.0.0
  sqlite3: 5.1.7
  stream-json: 1.9.1
  string-width: 7.2.0
  strip-ansi: 7.1.0
  stylelint: 16.21.0
  stylelint-config-standard: 38.0.0
  stylelint-config-standard-scss: 15.0.1
  stylelint-config-standard-vue: 1.0.0
  stylelint-use-logical: 2.1.2
  supertest: 7.0.0
  swagger-cli: 4.0.4
  swagger-ui-watcher: 2.1.14
  tar: 7.4.3
  tedious: 18.6.1
  tinymce: 6.8.5
  tmp: 0.2.3
  tsup: 8.4.0
  tsx: 4.19.3
  tus-js-client: 4.3.1
  typedoc: 0.27.9
  typedoc-plugin-frontmatter: 1.2.1
  typedoc-plugin-markdown: 4.4.2
  typedoc-plugin-zod: 1.3.1
  typedoc-vitepress-theme: 1.1.2
  typescript: 5.8.2
  typescript-eslint: 8.25.0
  undici: 7.5.0
  update-check: 1.5.4
  uuid: 11.1.0
  vite-plugin-dts: 4.5.1
  vite-plugin-vue-devtools: 7.7.2
  vite-tsconfig-paths: 5.1.4
  vitepress: 1.0.0-rc.4
  vitepress-plugin-tabs: 0.3.0
  vue: 3.5.13
  vue-i18n: 11.1.2
  vue-router: 4.5.0
  vue-tsc: 2.2.8
  vue-virtual-scroller: 2.0.0-beta.8
  vuedraggable: 4.1.0
  wellknown: 0.5.0
  ws: 8.18.1
  zod: 3.24.2
  zod-validation-error: 3.4.0
