packages:
  - directus
  - app
  - api
  - docs
  - sdk
  - packages/*
  - tests/*

onlyBuiltDependencies:
  - '@fortawesome/fontawesome-common-types'
  - '@fortawesome/fontawesome-svg-core'
  - '@fortawesome/free-regular-svg-icons'
  - '@fortawesome/free-solid-svg-icons'
  - '@parcel/watcher'
  - argon2
  - esbuild
  - isolated-vm
  - oracledb
  - sharp
  - sqlite3
  - vue-demi
