packages:
  - directus
  - app
  - api
  - docs
  - sdk
  - packages/*
  - tests/*

catalog:
  '@authenio/samlify-node-xmllint': 2.0.0
  '@aws-sdk/client-s3': 3.858.0
  '@aws-sdk/client-ses': 3.859.0
  '@aws-sdk/lib-storage': 3.858.0
  '@azure/storage-blob': 12.28.0
  '@changesets/get-github-info': 0.6.0
  '@changesets/types': 6.1.0
  '@directus/schema-builder': workspace:*
  '@directus/tsconfig': 3.0.0
  '@directus/types': workspace:*
  '@godaddy/terminus': 4.12.1
  '@google-cloud/storage': 7.16.0
  '@keyv/redis': 5.0.0
  '@ngneat/falso': 8.0.2
  '@npm/types': 2.1.0
  '@pnpm/logger': 1001.0.0
  '@pnpm/workspace.find-packages': 1000.0.31
  '@pnpm/workspace.pkgs-graph': 1000.0.18
  '@rollup/plugin-alias': 5.1.1
  '@rollup/plugin-commonjs': 28.0.6
  '@rollup/plugin-json': 6.1.0
  '@rollup/plugin-node-resolve': 16.0.1
  '@rollup/plugin-replace': 6.0.2
  '@rollup/plugin-terser': 0.4.4
  '@rollup/plugin-virtual': 3.0.2
  '@shopify/semaphore': 3.1.0
  '@smithy/node-http-handler': 4.1.0
  '@supabase/storage-js': 2.10.4
  '@tus/server': 2.3.0
  '@tus/utils': 0.6.0
  '@types/async': 3.2.24
  '@types/busboy': 1.5.4
  '@types/bytes': 3.1.5
  '@types/content-disposition': 0.5.9
  '@types/cookie-parser': 1.4.9
  '@types/cors': 2.8.19
  '@types/deep-diff': 1.0.5
  '@types/destroy': 1.0.3
  '@types/encodeurl': 1.0.3
  '@types/express-serve-static-core': 5.0.7
  '@types/express': 5.0.3
  '@types/fs-extra': 11.0.4
  '@types/glob-to-regexp': 0.4.4
  '@types/inquirer': 9.0.8
  '@types/js-yaml': 4.0.9
  '@types/json2csv': 5.0.7
  '@types/jsonwebtoken': 9.0.10
  '@types/ldapjs': 3.0.6
  '@types/lodash-es': 4.17.12
  '@types/mime-types': 3.0.1
  '@types/ms': 2.1.0
  '@types/node-schedule': 2.1.8
  '@types/node': 22.13.14
  '@types/nodemailer': 6.4.17
  '@types/object-hash': 3.0.6
  '@types/papaparse': 5.3.16
  '@types/proxy-addr': 2.0.3
  '@types/qs': 6.14.0
  '@types/sanitize-html': 2.16.0
  '@types/semver': 7.7.0
  '@types/stream-json': 1.7.8
  '@types/wellknown': 0.5.8
  '@types/ws': 8.18.1
  '@vitejs/plugin-vue': 6.0.1
  '@vitest/coverage-v8': 3.2.4
  '@vue/test-utils': 2.4.6
  argon2: 0.43.1
  async-mutex: 0.5.0
  async: 3.2.6
  axios-cache-interceptor: 1.8.0
  axios: 1.11.0
  boxen: 8.0.1
  busboy: 1.6.0
  bytes: 3.1.2
  camelcase: 8.0.0
  chalk: 5.4.1
  chokidar: 4.0.3
  commander: 14.0.0
  content-disposition: 0.5.4
  cookie-parser: 1.4.7
  cookie: 1.0.2
  copyfiles: 2.4.1
  cors: 2.8.5
  cron-parser: 5.3.0
  date-fns: 4.1.0
  deep-diff: 1.0.2
  destroy: 1.2.0
  dotenv: 17.2.1
  encodeurl: 2.0.0
  esbuild-plugin-replace: 1.4.0
  esbuild-yaml: 3.0.3
  esbuild: 0.25.8
  eventemitter2: 6.4.9
  execa: 9.6.0
  exif-reader: 2.0.2
  express: 5.1.0
  find-cache-directory: 6.0.0
  flat: 6.0.1
  form-data: 4.0.4
  fs-extra: 11.3.0
  get-port: 7.1.0
  glob-to-regexp: 0.4.1
  graphql-compose: 9.1.0
  graphql-ws: 6.0.6
  graphql: 16.11.0
  helmet: 8.1.0
  icc: 3.0.0
  inquirer: 12.9.0
  ioredis: 5.7.0
  ip-matching: 2.1.2
  isolated-vm: 6.0.1
  joi: 17.13.3
  js-yaml: 4.1.0
  js2xmlparser: 5.0.0
  json2csv: 5.0.7
  jsonwebtoken: 9.0.2
  keyv: 5.4.0
  knex-mock-client: 3.0.2
  knex: 3.1.0
  ky: 1.8.2
  ldapjs: 3.0.7
  liquidjs: 10.21.1
  lodash-es: 4.17.21
  log-symbols: 7.0.1
  marked: 16.1.1
  micromustache: 8.0.3
  mime-types: 3.0.1
  minimatch: 10.0.3
  mnemonist: 0.40.3
  ms: 2.1.3
  mysql2: 3.14.3
  nanoid: 5.1.5
  node-machine-id: 1.1.12
  node-schedule: 2.1.1
  nodemailer-mailgun-transport: 2.1.5
  nodemailer: 7.0.5
  npm-watch: 0.13.0
  object-hash: 3.0.0
  openapi3-ts: 4.5.0
  openid-client: 6.6.2
  ora: 8.2.0
  oracledb: 6.9.0
  otplib: 12.0.1
  p-limit: 6.2.0
  p-queue: 8.1.0
  papaparse: 5.5.3
  pg: 8.16.3
  pino-http-print: 3.1.0
  pino-http: 10.5.0
  pino-pretty: 13.1.1
  pino: 9.7.0
  pm2: 6.0.8
  prom-client: 15.1.3
  proxy-addr: 2.0.7
  qs: 6.14.0
  rate-limiter-flexible: 7.2.0
  rolldown: 1.0.0-beta.30
  rollup-plugin-esbuild: 6.2.1
  rollup-plugin-styler: 2.0.0
  rollup: 4.46.2
  samlify: 2.10.1
  sanitize-html: 2.17.0
  semver: 7.7.2
  sharp: 0.34.3
  snappy: 7.3.0
  sqlite3: 5.1.7
  stream-json: 1.9.1
  strip-ansi: 7.1.0
  swagger-cli: 4.0.4
  swagger-ui-watcher: 2.1.14
  tar: 7.4.3
  tedious: 18.6.1
  tsup: 8.5.0
  tsx: 4.20.3
  tus-js-client: 4.3.1
  typescript: 5.8.3
  undici: 7.13.0
  update-check: 1.5.4
  uuid: 11.1.0
  vite: 7.0.6
  vitest: 3.2.4
  vue: 3.5.18
  wellknown: 0.5.0
  ws: 8.18.3
  zod-validation-error: 4.0.1
  zod: 4.0.14

catalogMode: strict

onlyBuiltDependencies:
  - '@fortawesome/fontawesome-common-types'
  - '@fortawesome/fontawesome-svg-core'
  - '@fortawesome/free-regular-svg-icons'
  - '@fortawesome/free-solid-svg-icons'
  - '@parcel/watcher'
  - argon2
  - esbuild
  - isolated-vm
  - oracledb
  - sharp
  - sqlite3
  - vue-demi
