packages:
  - directus
  - app
  - api
  - docs
  - sdk
  - packages/*
  - tests/*

catalog:
  '@directus/tsconfig': 3.0.0
  '@types/lodash-es': 4.17.12
  '@types/node': 22.13.14
  '@vitest/coverage-v8': 3.2.4
  '@vue/test-utils': 2.4.6
  axios: 1.11.0
  chalk: 5.4.1
  commander: 14.0.0
  execa: 9.6.0
  fs-extra: 11.3.0
  inquirer: 12.9.0
  lodash-es: 4.17.21
  log-symbols: 7.0.1
  nanoid: 5.1.5
  ora: 8.2.0
  tsup: 8.5.0
  typescript: 5.8.3
  update-check: 1.5.4
  vitest: 3.2.4
  vue: 3.5.18

catalogMode: strict

onlyBuiltDependencies:
  - '@fortawesome/fontawesome-common-types'
  - '@fortawesome/fontawesome-svg-core'
  - '@fortawesome/free-regular-svg-icons'
  - '@fortawesome/free-solid-svg-icons'
  - '@parcel/watcher'
  - argon2
  - esbuild
  - isolated-vm
  - oracledb
  - sharp
  - sqlite3
  - vue-demi
