name: Preview Deployment

on:
  pull_request_target:
    types: [labeled, synchronize]

permissions:
  contents: read
  pull-requests: write

env:
  EXPIRATION_HOURS: 2

jobs:
  preview-labeled:
    if:
      (github.event.action == 'labeled' && github.event.label.name == 'Preview') || (github.event.action ==
      'synchronize' && contains(github.event.pull_request.labels.*.name, 'Preview'))
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: preview-label-${{ github.event.pull_request.number }}
      cancel-in-progress: false
    steps:
      - name: Call NF deploy webhook
        env:
          NEXT_BRANCH: ${{ github.event.pull_request.head.ref }}
          PREVIEW_TOKEN: ${{ secrets.NORTHFLANK_PREVIEW_TOKEN }}
          PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
          REPO_URL: ${{ github.event.pull_request.head.repo.clone_url }}
        run: |
          curl -G "https://webhooks.northflank.com/previews/${PREVIEW_TOKEN}" \
          --data-urlencode "preview-source.pullRequestId=${PULL_REQUEST_ID}" \
          --data-urlencode "preview-source.repoUrl=${REPO_URL}" \
          --data-urlencode "next.branch=${NEXT_BRANCH}"
