import { DeepPartial, Field } from '@directus/types';

export const themingFields: DeepPartial<Field>[] = [
	{
		collection: 'directus_settings',
		name: 'Theming Group',
		field: 'theming_group',
		type: 'alias',
		schema: null,
		meta: {
			system: true,
			collection: 'directus_settings',
			field: 'theming_group',
			special: ['alias', 'no-data', 'group'],
			interface: 'group-raw',
			options: null,
			display: null,
			display_options: null,
			readonly: false,
			hidden: false,
			width: 'full',
			group: null,
			translations: null,
			note: null,
			conditions: null,
			required: false,
		},
	},
	{
		collection: 'directus_settings',
		field: 'default_appearance',
		type: 'string',
		schema: {
			name: 'default_appearance',
			table: 'directus_settings',
			data_type: 'varchar',
			default_value: 'auto',
			max_length: 255,
			numeric_precision: null,
			numeric_scale: null,
			is_generated: false,
			generation_expression: null,
			is_nullable: false,
			is_unique: false,
			is_primary_key: false,
			has_auto_increment: false,
			foreign_key_column: null,
			foreign_key_table: null,
		},
		meta: {
			system: true,
			collection: 'directus_settings',
			field: 'default_appearance',
			special: null,
			interface: 'select-dropdown',
			options: {
				choices: [
					{ value: 'auto', text: '$t:appearance_auto' },
					{ value: 'light', text: '$t:appearance_light' },
					{ value: 'dark', text: '$t:appearance_dark' },
				],
			},
			display: null,
			display_options: null,
			readonly: false,
			hidden: false,
			width: 'half',
			group: 'theming_group',
			translations: null,
			note: null,
			conditions: null,
			required: false,
		},
		name: 'Default Appearance',
	},
	{
		collection: 'directus_settings',
		field: 'default_theme_light',
		type: 'string',
		schema: {
			name: 'default_theme_light',
			table: 'directus_settings',
			data_type: 'varchar',
			default_value: null,
			max_length: 255,
			numeric_precision: null,
			numeric_scale: null,
			is_generated: false,
			generation_expression: null,
			is_nullable: true,
			is_unique: false,
			is_primary_key: false,
			has_auto_increment: false,
			foreign_key_column: null,
			foreign_key_table: null,
		},
		meta: {
			system: true,
			collection: 'directus_settings',
			field: 'default_theme_light',
			special: null,
			interface: 'system-theme',
			options: { appearance: 'light' },
			display: null,
			display_options: null,
			readonly: false,
			hidden: false,
			width: 'full',
			group: 'theming_group',
			translations: null,
			note: null,
			conditions: null,
			required: false,
		},
		name: 'Default Theme Light',
	},
	{
		collection: 'directus_settings',
		field: 'default_theme_dark',
		type: 'string',
		schema: {
			name: 'default_theme_dark',
			table: 'directus_settings',
			data_type: 'varchar',
			default_value: null,
			max_length: 255,
			numeric_precision: null,
			numeric_scale: null,
			is_generated: false,
			generation_expression: null,
			is_nullable: true,
			is_unique: false,
			is_primary_key: false,
			has_auto_increment: false,
			foreign_key_column: null,
			foreign_key_table: null,
		},
		meta: {
			system: true,
			collection: 'directus_settings',
			field: 'default_theme_dark',
			special: null,
			interface: 'system-theme',
			options: { appearance: 'dark' },
			display: null,
			display_options: null,
			readonly: false,
			hidden: false,
			width: 'full',
			group: 'theming_group',
			translations: null,
			note: null,
			conditions: null,
			required: false,
		},
		name: 'Default Theme Dark',
	},
];
