import { DeepPartial, Field } from '@directus/types';

export const themingUserFields: DeepPartial<Field>[] = [
	{
		collection: 'directus_users',
		field: 'appearance',
		type: 'string',
		schema: {
			name: 'appearance',
			table: 'directus_users',
			data_type: 'varchar',
			default_value: null,
			max_length: 255,
			numeric_precision: null,
			numeric_scale: null,
			is_generated: false,
			generation_expression: null,
			is_nullable: true,
			is_unique: false,
			is_primary_key: false,
			has_auto_increment: false,
			foreign_key_column: null,
			foreign_key_table: null,
		},
		meta: {
			system: true,
			collection: 'directus_users',
			field: 'appearance',
			special: null,
			interface: 'select-dropdown',
			options: {
				choices: [
					{ value: null, text: '$t:default_sync_with_project' },
					{ value: 'auto', text: '$t:appearance_auto' },
					{ value: 'light', text: '$t:appearance_light' },
					{ value: 'dark', text: '$t:appearance_dark' },
				],
			},
			display: null,
			display_options: null,
			readonly: false,
			hidden: false,
			sort: 15,
			width: 'half',
			group: null,
			translations: null,
			note: null,
			conditions: null,
			required: false,
		},
		name: '$t:settings_appearance',
	},
	{
		collection: 'directus_users',
		field: 'theme_light',
		type: 'string',
		schema: {
			// name: 'theme_light',
			table: 'directus_users',
			data_type: 'varchar',
			default_value: null,
			max_length: 255,
			numeric_precision: null,
			numeric_scale: null,
			is_generated: false,
			generation_expression: null,
			is_nullable: true,
			is_unique: false,
			is_primary_key: false,
			has_auto_increment: false,
			foreign_key_column: null,
			foreign_key_table: null,
		},
		meta: {
			system: true,
			collection: 'directus_users',
			field: 'theme_light',
			special: null,
			interface: 'system-theme',
			options: { appearance: 'light', includeNull: true },
			display: null,
			display_options: null,
			readonly: false,
			hidden: false,
			width: 'full',
			group: null,
			translations: null,
			note: null,
			conditions: null,
			required: false,
		},
		name: '$t:theme_light',
	},
	{
		collection: 'directus_users',
		name: '$t:theme_dark',
		field: 'theme_dark',
		type: 'string',
		meta: {
			collection: 'directus_users',
			field: 'theme_dark',
			interface: 'system-theme',
			options: { appearance: 'dark', includeNull: true },
			width: 'full',
		},
	},
];
