summary: Create Multiple Roles
description: Create multiple new roles.
operationId: createRoles
parameters:
- $ref: ../../components/parameters.yaml#/Fields
- $ref: ../../components/parameters.yaml#/Limit
- $ref: ../../components/parameters.yaml#/Meta
- $ref: ../../components/parameters.yaml#/Offset
- $ref: ../../components/parameters.yaml#/Sort
- $ref: ../../components/parameters.yaml#/Filter
- $ref: ../../components/parameters.yaml#/Search
requestBody:
  content:
    application/json:
      schema:
        type: object
        properties:
          data:
            type: array
            items:
              $ref: ../../components/schemas/roles.yaml
responses:
  '200':
    description: Successful request
    content:
      application/json:
        schema:
          type: object
          properties:
            data:
              type: array
              items:
                $ref: ../../components/schemas/roles.yaml
            meta:
              $ref: ../../components/schemas/x-metadata.yaml
  '401':
    $ref: ../../components/responses.yaml#/UnauthorizedError
  '404':
    $ref: ../../components/responses.yaml#/NotFoundError
security: []
tags:
- Roles
x-codeSamples:
- label: Directus SDK
  lang: JavaScript
  source: |
    import { createDirectus, rest, createRoles } from '@directus/sdk';

    const client = createDirectus('directus_project_url').with(rest());

    const result = await client.request(createRoles(roles_object_array));
- label: GraphQL
  lang: GraphQL
  source: |
    POST /graphql/system

    type Mutation {
      create_roles_items(data: [create_directus_roles_input!]!): [directus_roles]
    }
