summary: Delete Multiple Roles
description: Delete multiple existing roles.
operationId: deleteRoles
requestBody:
  description: An array of role primary keys.
  content:
    application/json:
      schema:
        type: array
        items:
          type: string
responses:
  '204':
    description: The resource was deleted successfully.
  '401':
    $ref: ../../components/responses.yaml#/UnauthorizedError
security: []
tags:
- Roles
x-codeSamples:
- label: Directus SDK
  lang: JavaScript
  source: |
    import { createDirectus, rest, deleteRoles } from '@directus/sdk';

    const client = createDirectus('directus_project_url').with(rest());

    const result = await client.request(deleteRoles(role_id_array));
- label: GraphQL
  lang: GraphQL
  source: |
    POST /graphql/system

    type Mutation {
    	delete_roles_items(ids: [ID!]!): delete_many
    }
