summary: Delete a Role
description: Delete an existing role.
operationId: deleteRole
responses:
  '204':
    description: The resource was deleted successfully.
  '401':
    $ref: ../../../components/responses.yaml#/UnauthorizedError
  '404':
    $ref: ../../../components/responses.yaml#/NotFoundError
security: []
tags:
- Roles
parameters:
- $ref: ../../../components/parameters.yaml#/UUId
x-codeSamples:
- label: Directus SDK
  lang: JavaScript
  source: |
    import { createDirectus, rest, deleteRole } from '@directus/sdk';

    const client = createDirectus('directus_project_url').with(rest());

    const result = await client.request(deleteRole(role_id));
- label: GraphQL
  lang: GraphQL
  source: |
    POST /graphql/system

    type Mutation {
    	delete_roles_item(id: ID!): delete_one
    }
