export const DIRECTUS_LICENSE_BASE_URL = 'https://keys.licit.dev';
export const DIRECTUS_LICENSE_VERSION = '2026-02-18';
export const DEFAULT_ONBOARDING_GRACE_DAYS = 30;
export const DEFAULT_ONBOARDING_GRACE_MS = DEFAULT_ONBOARDING_GRACE_DAYS * 24 * 60 * 60 * 1000;
