name: Report a bug
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Hi, thank you for taking the time to create an issue! Before you get started, please ensure the following are correct:

        - I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
        - I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
        - There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.

        _For issues specific to Directus Cloud projects, please reach out through the Live Chat in our Cloud Dashboard._
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description:
        Steps to reproduce the behavior. Contributors should be able to follow the steps provided in order to reproduce
        the bug.
    validations:
      required: true
  - type: input
    attributes:
      label: Directus Version
      placeholder: v10.x.x
    validations:
      required: true
  - type: dropdown
    id: deployment
    attributes:
      label: Hosting Strategy
      options:
        - Self-Hosted (Docker Image)
        - Self-Hosted (Custom)
        - Directus Cloud
    validations:
      required: true
  - type: input
    attributes:
      label: Database
      description: If applicable, the vendor and version of the database being used. For example, PostgreSQL 16.
