name: Bug Report
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Hi, thank you for taking the time to create an issue!

        Before opening this issue, please make sure that:

        - You've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
        - You're using [the latest version of Directus](https://github.com/directus/directus/releases).
        - There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.

        _For issues specific to Directus Cloud projects, please reach out through the Live Chat in our Cloud Dashboard._
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description:
        Steps to reproduce the behavior. Contributors should be able to follow the steps provided in order to reproduce
        the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Errors Shown
      description: Are there any errors logged in the browser console, or terminal where you're running Directus?
  - type: input
    id: directus-version
    attributes:
      label: What version of Directus are you using?
      description: 'Version is displayed under "Settings". For example: 9.0.1'
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: What version of Node.js are you using?
      description: 'For example: 12.0.0'
    validations:
      required: true
  - type: input
    attributes:
      label: What database are you using?
      description: 'For example: Postgres 13, SQLite 3.31.0'
    validations:
      required: true
  - type: input
    attributes:
      label: What browser are you using?
      description: 'For example: Chrome, Safari'
    validations:
      required: true
  - type: input
    attributes:
      label: How are you deploying Directus?
      description: 'For example: running locally, Docker, PaaS'
    validations:
      required: true
