export const relations = [
	{
		collection: 'directus_folders',
		field: 'parent',
		related_collection: 'directus_folders',
		schema: {
			table: 'directus_folders',
			column: 'parent',
			foreign_key_table: 'directus_folders',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'NO ACTION',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_folders',
			many_field: 'parent',
			one_collection: 'directus_folders',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_files',
		field: 'folder',
		related_collection: 'directus_folders',
		schema: {
			table: 'directus_files',
			column: 'folder',
			foreign_key_table: 'directus_folders',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'SET NULL',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_files',
			many_field: 'folder',
			one_collection: 'directus_folders',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_files',
		field: 'modified_by',
		related_collection: 'directus_users',
		schema: {
			table: 'directus_files',
			column: 'modified_by',
			foreign_key_table: 'directus_users',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'NO ACTION',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_files',
			many_field: 'modified_by',
			one_collection: 'directus_users',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_files',
		field: 'uploaded_by',
		related_collection: 'directus_users',
		schema: {
			table: 'directus_files',
			column: 'uploaded_by',
			foreign_key_table: 'directus_users',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'NO ACTION',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_files',
			many_field: 'uploaded_by',
			one_collection: 'directus_users',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_operations',
		field: 'user_created',
		related_collection: 'directus_users',
		schema: {
			table: 'directus_operations',
			column: 'user_created',
			foreign_key_table: 'directus_users',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'SET NULL',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_operations',
			many_field: 'user_created',
			one_collection: 'directus_users',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_operations',
		field: 'flow',
		related_collection: 'directus_flows',
		schema: {
			table: 'directus_operations',
			column: 'flow',
			foreign_key_table: 'directus_flows',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'CASCADE',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_operations',
			many_field: 'flow',
			one_collection: 'directus_flows',
			one_field: 'operations',
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'delete',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_operations',
		field: 'reject',
		related_collection: 'directus_operations',
		schema: {
			table: 'directus_operations',
			column: 'reject',
			foreign_key_table: 'directus_operations',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'NO ACTION',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_operations',
			many_field: 'reject',
			one_collection: 'directus_operations',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_operations',
		field: 'resolve',
		related_collection: 'directus_operations',
		schema: {
			table: 'directus_operations',
			column: 'resolve',
			foreign_key_table: 'directus_operations',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'NO ACTION',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_operations',
			many_field: 'resolve',
			one_collection: 'directus_operations',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_notifications',
		field: 'sender',
		related_collection: 'directus_users',
		schema: {
			table: 'directus_notifications',
			column: 'sender',
			foreign_key_table: 'directus_users',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'NO ACTION',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_notifications',
			many_field: 'sender',
			one_collection: 'directus_users',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_notifications',
		field: 'recipient',
		related_collection: 'directus_users',
		schema: {
			table: 'directus_notifications',
			column: 'recipient',
			foreign_key_table: 'directus_users',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'CASCADE',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_notifications',
			many_field: 'recipient',
			one_collection: 'directus_users',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_shares',
		field: 'user_created',
		related_collection: 'directus_users',
		schema: {
			table: 'directus_shares',
			column: 'user_created',
			foreign_key_table: 'directus_users',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'SET NULL',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_shares',
			many_field: 'user_created',
			one_collection: 'directus_users',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_shares',
		field: 'role',
		related_collection: 'directus_roles',
		schema: {
			table: 'directus_shares',
			column: 'role',
			foreign_key_table: 'directus_roles',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'CASCADE',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_shares',
			many_field: 'role',
			one_collection: 'directus_roles',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_shares',
		field: 'collection',
		related_collection: 'directus_collections',
		schema: {
			table: 'directus_shares',
			column: 'collection',
			foreign_key_table: 'directus_collections',
			foreign_key_column: 'collection',
			on_update: 'NO ACTION',
			on_delete: 'CASCADE',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_shares',
			many_field: 'collection',
			one_collection: 'directus_collections',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_versions',
		field: 'user_updated',
		related_collection: 'directus_users',
		schema: {
			table: 'directus_versions',
			column: 'user_updated',
			foreign_key_table: 'directus_users',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'NO ACTION',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_versions',
			many_field: 'user_updated',
			one_collection: 'directus_users',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_versions',
		field: 'user_created',
		related_collection: 'directus_users',
		schema: {
			table: 'directus_versions',
			column: 'user_created',
			foreign_key_table: 'directus_users',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'SET NULL',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_versions',
			many_field: 'user_created',
			one_collection: 'directus_users',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_versions',
		field: 'collection',
		related_collection: 'directus_collections',
		schema: {
			table: 'directus_versions',
			column: 'collection',
			foreign_key_table: 'directus_collections',
			foreign_key_column: 'collection',
			on_update: 'NO ACTION',
			on_delete: 'CASCADE',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_versions',
			many_field: 'collection',
			one_collection: 'directus_collections',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_revisions',
		field: 'version',
		related_collection: 'directus_versions',
		schema: {
			table: 'directus_revisions',
			column: 'version',
			foreign_key_table: 'directus_versions',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'CASCADE',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_revisions',
			many_field: 'version',
			one_collection: 'directus_versions',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_revisions',
		field: 'activity',
		related_collection: 'directus_activity',
		schema: {
			table: 'directus_revisions',
			column: 'activity',
			foreign_key_table: 'directus_activity',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'CASCADE',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_revisions',
			many_field: 'activity',
			one_collection: 'directus_activity',
			one_field: 'revisions',
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_revisions',
		field: 'parent',
		related_collection: 'directus_revisions',
		schema: {
			table: 'directus_revisions',
			column: 'parent',
			foreign_key_table: 'directus_revisions',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'NO ACTION',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_revisions',
			many_field: 'parent',
			one_collection: 'directus_revisions',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_sessions',
		field: 'share',
		related_collection: 'directus_shares',
		schema: {
			table: 'directus_sessions',
			column: 'share',
			foreign_key_table: 'directus_shares',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'CASCADE',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_sessions',
			many_field: 'share',
			one_collection: 'directus_shares',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_sessions',
		field: 'user',
		related_collection: 'directus_users',
		schema: {
			table: 'directus_sessions',
			column: 'user',
			foreign_key_table: 'directus_users',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'CASCADE',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_sessions',
			many_field: 'user',
			one_collection: 'directus_users',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_webhooks',
		field: 'migrated_flow',
		related_collection: 'directus_flows',
		schema: {
			table: 'directus_webhooks',
			column: 'migrated_flow',
			foreign_key_table: 'directus_flows',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'SET NULL',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_webhooks',
			many_field: 'migrated_flow',
			one_collection: 'directus_flows',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_permissions',
		field: 'policy',
		related_collection: 'directus_policies',
		schema: {
			table: 'directus_permissions',
			column: 'policy',
			foreign_key_table: 'directus_policies',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'CASCADE',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_permissions',
			many_field: 'policy',
			one_collection: 'directus_policies',
			one_field: 'permissions',
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'delete',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_access',
		field: 'policy',
		related_collection: 'directus_policies',
		schema: {
			table: 'directus_access',
			column: 'policy',
			foreign_key_table: 'directus_policies',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'CASCADE',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_access',
			many_field: 'policy',
			one_collection: 'directus_policies',
			one_field: 'roles',
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'delete',
			junction_field: 'role',
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_access',
		field: 'user',
		related_collection: 'directus_users',
		schema: {
			table: 'directus_access',
			column: 'user',
			foreign_key_table: 'directus_users',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'CASCADE',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_access',
			many_field: 'user',
			one_collection: 'directus_users',
			one_field: 'policies',
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'delete',
			junction_field: 'policy',
			sort_field: 'sort',
			system: true,
		},
	},
	{
		collection: 'directus_access',
		field: 'role',
		related_collection: 'directus_roles',
		schema: {
			table: 'directus_access',
			column: 'role',
			foreign_key_table: 'directus_roles',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'CASCADE',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_access',
			many_field: 'role',
			one_collection: 'directus_roles',
			one_field: 'policies',
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'delete',
			junction_field: 'policy',
			sort_field: 'sort',
			system: true,
		},
	},
	{
		collection: 'directus_collections',
		field: 'group',
		related_collection: 'directus_collections',
		schema: {
			table: 'directus_collections',
			column: 'group',
			foreign_key_table: 'directus_collections',
			foreign_key_column: 'collection',
			on_update: 'NO ACTION',
			on_delete: 'NO ACTION',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_collections',
			many_field: 'group',
			one_collection: 'directus_collections',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_dashboards',
		field: 'user_created',
		related_collection: 'directus_users',
		schema: {
			table: 'directus_dashboards',
			column: 'user_created',
			foreign_key_table: 'directus_users',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'SET NULL',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_dashboards',
			many_field: 'user_created',
			one_collection: 'directus_users',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_flows',
		field: 'user_created',
		related_collection: 'directus_users',
		schema: {
			table: 'directus_flows',
			column: 'user_created',
			foreign_key_table: 'directus_users',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'SET NULL',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_flows',
			many_field: 'user_created',
			one_collection: 'directus_users',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_panels',
		field: 'user_created',
		related_collection: 'directus_users',
		schema: {
			table: 'directus_panels',
			column: 'user_created',
			foreign_key_table: 'directus_users',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'SET NULL',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_panels',
			many_field: 'user_created',
			one_collection: 'directus_users',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_panels',
		field: 'dashboard',
		related_collection: 'directus_dashboards',
		schema: {
			table: 'directus_panels',
			column: 'dashboard',
			foreign_key_table: 'directus_dashboards',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'CASCADE',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_panels',
			many_field: 'dashboard',
			one_collection: 'directus_dashboards',
			one_field: 'panels',
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_presets',
		field: 'role',
		related_collection: 'directus_roles',
		schema: {
			table: 'directus_presets',
			column: 'role',
			foreign_key_table: 'directus_roles',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'CASCADE',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_presets',
			many_field: 'role',
			one_collection: 'directus_roles',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_presets',
		field: 'user',
		related_collection: 'directus_users',
		schema: {
			table: 'directus_presets',
			column: 'user',
			foreign_key_table: 'directus_users',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'CASCADE',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_presets',
			many_field: 'user',
			one_collection: 'directus_users',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_roles',
		field: 'parent',
		related_collection: 'directus_roles',
		schema: {
			table: 'directus_roles',
			column: 'parent',
			foreign_key_table: 'directus_roles',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'NO ACTION',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_roles',
			many_field: 'parent',
			one_collection: 'directus_roles',
			one_field: 'children',
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_comments',
		field: 'user_updated',
		related_collection: 'directus_users',
		schema: {
			table: 'directus_comments',
			column: 'user_updated',
			foreign_key_table: 'directus_users',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'NO ACTION',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_comments',
			many_field: 'user_updated',
			one_collection: 'directus_users',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_comments',
		field: 'user_created',
		related_collection: 'directus_users',
		schema: {
			table: 'directus_comments',
			column: 'user_created',
			foreign_key_table: 'directus_users',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'SET NULL',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_comments',
			many_field: 'user_created',
			one_collection: 'directus_users',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_users',
		field: 'role',
		related_collection: 'directus_roles',
		schema: {
			table: 'directus_users',
			column: 'role',
			foreign_key_table: 'directus_roles',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'SET NULL',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_users',
			many_field: 'role',
			one_collection: 'directus_roles',
			one_field: 'users',
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'links',
		field: 'article_id',
		related_collection: 'articles',
		schema: {
			table: 'links',
			column: 'article_id',
			foreign_key_table: 'articles',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'SET NULL',
			constraint_name: null,
		},
		meta: {
			id: 6,
			many_collection: 'links',
			many_field: 'article_id',
			one_collection: 'articles',
			one_field: 'links',
			one_collection_field: null,
			one_allowed_collections: null,
			junction_field: null,
			sort_field: null,
			one_deselect_action: 'nullify',
		},
	},
	{
		collection: 'articles',
		field: 'author',
		related_collection: 'users',
		schema: {
			table: 'articles',
			column: 'author',
			foreign_key_table: 'users',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'SET NULL',
			constraint_name: null,
		},
		meta: {
			id: 10,
			many_collection: 'articles',
			many_field: 'author',
			one_collection: 'users',
			one_field: null,
			one_collection_field: null,
			one_allowed_collections: null,
			junction_field: null,
			sort_field: null,
			one_deselect_action: 'nullify',
		},
	},
	{
		collection: 'articles_sections',
		field: 'articles_id',
		related_collection: 'articles',
		schema: {
			table: 'articles_sections',
			column: 'articles_id',
			foreign_key_table: 'articles',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'SET NULL',
			constraint_name: null,
		},
		meta: {
			id: 12,
			many_collection: 'articles_sections',
			many_field: 'articles_id',
			one_collection: 'articles',
			one_field: 'sections',
			one_collection_field: null,
			one_allowed_collections: null,
			junction_field: 'item',
			sort_field: null,
			one_deselect_action: 'nullify',
		},
	},
	{
		collection: 'articles_tags',
		field: 'articles_id',
		related_collection: 'articles',
		schema: {
			table: 'articles_tags',
			column: 'articles_id',
			foreign_key_table: 'articles',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'SET NULL',
			constraint_name: null,
		},
		meta: {
			id: 14,
			many_collection: 'articles_tags',
			many_field: 'articles_id',
			one_collection: 'articles',
			one_field: 'tags',
			one_collection_field: null,
			one_allowed_collections: null,
			junction_field: 'tags_id',
			sort_field: null,
			one_deselect_action: 'nullify',
		},
	},
	{
		collection: 'articles_tags',
		field: 'tags_id',
		related_collection: 'tags',
		schema: {
			table: 'articles_tags',
			column: 'tags_id',
			foreign_key_table: 'tags',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'SET NULL',
			constraint_name: null,
		},
		meta: {
			id: 13,
			many_collection: 'articles_tags',
			many_field: 'tags_id',
			one_collection: 'tags',
			one_field: null,
			one_collection_field: null,
			one_allowed_collections: null,
			junction_field: 'articles_id',
			sort_field: null,
			one_deselect_action: 'nullify',
		},
	},
	{
		collection: 'directus_settings',
		field: 'public_registration_role',
		related_collection: 'directus_roles',
		schema: {
			table: 'directus_settings',
			column: 'public_registration_role',
			foreign_key_table: 'directus_roles',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'SET NULL',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_settings',
			many_field: 'public_registration_role',
			one_collection: 'directus_roles',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_settings',
		field: 'public_favicon',
		related_collection: 'directus_files',
		schema: {
			table: 'directus_settings',
			column: 'public_favicon',
			foreign_key_table: 'directus_files',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'NO ACTION',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_settings',
			many_field: 'public_favicon',
			one_collection: 'directus_files',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_settings',
		field: 'storage_default_folder',
		related_collection: 'directus_folders',
		schema: {
			table: 'directus_settings',
			column: 'storage_default_folder',
			foreign_key_table: 'directus_folders',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'SET NULL',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_settings',
			many_field: 'storage_default_folder',
			one_collection: 'directus_folders',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_settings',
		field: 'public_background',
		related_collection: 'directus_files',
		schema: {
			table: 'directus_settings',
			column: 'public_background',
			foreign_key_table: 'directus_files',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'NO ACTION',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_settings',
			many_field: 'public_background',
			one_collection: 'directus_files',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_settings',
		field: 'public_foreground',
		related_collection: 'directus_files',
		schema: {
			table: 'directus_settings',
			column: 'public_foreground',
			foreign_key_table: 'directus_files',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'NO ACTION',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_settings',
			many_field: 'public_foreground',
			one_collection: 'directus_files',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_settings',
		field: 'project_logo',
		related_collection: 'directus_files',
		schema: {
			table: 'directus_settings',
			column: 'project_logo',
			foreign_key_table: 'directus_files',
			foreign_key_column: 'id',
			on_update: 'NO ACTION',
			on_delete: 'NO ACTION',
			constraint_name: null,
		},
		meta: {
			many_collection: 'directus_settings',
			many_field: 'project_logo',
			one_collection: 'directus_files',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'articles_sections',
		field: 'item',
		related_collection: null,
		schema: null,
		meta: {
			id: 11,
			many_collection: 'articles_sections',
			many_field: 'item',
			one_collection: null,
			one_field: null,
			one_collection_field: 'collection',
			one_allowed_collections: ['sec_num', 'sec_text'],
			junction_field: 'articles_id',
			sort_field: null,
			one_deselect_action: 'nullify',
		},
	},
	{
		collection: 'directus_comments',
		field: 'collection',
		related_collection: 'directus_collections',
		schema: null,
		meta: {
			many_collection: 'directus_comments',
			many_field: 'collection',
			one_collection: 'directus_collections',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_users',
		field: 'avatar',
		related_collection: 'directus_files',
		schema: null,
		meta: {
			many_collection: 'directus_users',
			many_field: 'avatar',
			one_collection: 'directus_files',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_fields',
		field: 'collection',
		related_collection: 'directus_collections',
		schema: null,
		meta: {
			many_collection: 'directus_fields',
			many_field: 'collection',
			one_collection: 'directus_collections',
			one_field: 'fields',
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_fields',
		field: 'group',
		related_collection: 'directus_fields',
		schema: null,
		meta: {
			many_collection: 'directus_fields',
			many_field: 'group',
			one_collection: 'directus_fields',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_activity',
		field: 'user',
		related_collection: 'directus_users',
		schema: null,
		meta: {
			many_collection: 'directus_activity',
			many_field: 'user',
			one_collection: 'directus_users',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_flows',
		field: 'operation',
		related_collection: 'directus_operations',
		schema: null,
		meta: {
			many_collection: 'directus_flows',
			many_field: 'operation',
			one_collection: 'directus_operations',
			one_field: null,
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'nullify',
			junction_field: null,
			sort_field: null,
			system: true,
		},
	},
	{
		collection: 'directus_access',
		field: 'policy',
		related_collection: 'directus_policies',
		schema: null,
		meta: {
			many_collection: 'directus_access',
			many_field: 'policy',
			one_collection: 'directus_policies',
			one_field: 'users',
			one_allowed_collections: null,
			one_collection_field: null,
			one_deselect_action: 'delete',
			junction_field: 'user',
			sort_field: null,
			system: true,
		},
	},
] as const;
