FROM node:alpine-16

RUN \
  # Upgrade system and install 'ssmtp' to be able to send mails
  apk upgrade --no-cache && apk add --no-cache \
  ssmtp

WORKDIR /directus

ADD . .

RUN npm i

RUN \
  # Create data directories
  mkdir -p \
    database \
    extensions \
    uploads

# Expose data directories as volumes
VOLUME \
  /directus/database \
  /directus/extensions \
  /directus/uploads

EXPOSE 8055
EXPOSE 8080
CMD npm run dev
