import ExportSidebarDetail from '@/views/private/components/export-sidebar-detail.vue';
import RenderDisplay from '@/views/private/components/render-display.vue';
import RenderTemplate from '@/views/private/components/render-template.vue';
import SidebarDetail from '@/views/private/components/sidebar-detail.vue';
import UserPopover from '@/views/private/components/user-popover.vue';
import ValueNull from '@/views/private/components/value-null.vue';
import DocsWrapper from '@/views/private/components/docs-wrapper.vue';
import DrawerItem from '@/views/private/components/drawer-item.vue';
import DrawerBatch from '@/views/private/components/drawer-batch.vue';
import { App } from 'vue';
import TransitionBounce from '@directus/components/transition/bounce.vue';
import TransitionDialog from '@directus/components/transition/dialog.vue';
import TransitionExpand from '@directus/components/transition/expand.vue';
import VAvatar from '@directus/components/v-avatar.vue';
import VBadge from '@directus/components/v-badge.vue';
import VBreadcrumb from '@directus/components/v-breadcrumb.vue';
import VButton from '@directus/components/v-button.vue';
import VCard from '@directus/components/v-card.vue';
import VCardActions from '@directus/components/v-card-actions.vue';
import VCardSubtitle from '@directus/components/v-card-subtitle.vue';
import VCardText from '@directus/components/v-card-text.vue';
import VCardTitle from '@directus/components/v-card-title.vue';
import VCheckbox from '@directus/components/v-checkbox.vue';
import VCheckboxTree from '@directus/components/v-checkbox-tree/v-checkbox-tree.vue';
import VChip from '@directus/components/v-chip.vue';
import VDetail from './v-detail.vue';
import VDialog from './v-dialog.vue';
import VDivider from '@directus/components/v-divider.vue';
import VDrawer from './v-drawer.vue';
import VError from './v-error.vue';
import VFancySelect from '@directus/components/v-fancy-select.vue';
import VFieldTemplate from './v-field-template/v-field-template.vue';
import VFieldList from './v-field-list/v-field-list.vue';
import VForm from './v-form/v-form.vue';
import VHover from '@directus/components/v-hover.vue';
import VHighlight from '@directus/components/v-highlight.vue';
import VIcon from '@directus/components/v-icon/v-icon.vue';
import VImage from './v-image.vue';
import VIconFile from '@directus/components/v-icon-file.vue';
import VInfo from '@directus/components/v-info.vue';
import VInput from '@directus/components/v-input.vue';
import VItemGroup from '@directus/components/v-item-group.vue';
import VItem from '@directus/components/v-item.vue';
import VList from '@directus/components/v-list.vue';
import VListGroup from '@directus/components/v-list-group.vue';
import VListItem from '@directus/components/v-list-item.vue';
import VListItemContent from '@directus/components/v-list-item-content.vue';
import VListItemHint from '@directus/components/v-list-item-hint.vue';
import VListItemIcon from '@directus/components/v-list-item-icon.vue';
import VMenu from '@directus/components/v-menu.vue';
import VNotice from '@directus/components/v-notice.vue';
import VOverlay from '@directus/components/v-overlay.vue';
import VPagination from '@directus/components/v-pagination.vue';
import VProgressCircular from '@directus/components/v-progress-circular.vue';
import VProgressLinear from '@directus/components/v-progress-linear.vue';
import VRadio from '@directus/components/v-radio.vue';
import VSelect from '@directus/components/v-select/v-select.vue';
import VSheet from '@directus/components/v-sheet.vue';
import VSkeletonLoader from '@directus/components/v-skeleton-loader.vue';
import VSlider from '@directus/components/v-slider.vue';
import VTable from './v-table/v-table.vue';
import VTabs from '@directus/components/v-tabs.vue';
import VTab from '@directus/components/v-tab.vue';
import VTabItem from '@directus/components/v-tab-item.vue';
import VTabsItems from '@directus/components/v-tabs-items.vue';
import VTemplateInput from '@directus/components/v-template-input.vue';
import VTextOverflow from '@directus/components/v-text-overflow.vue';
import VTextarea from '@directus/components/v-textarea.vue';
import VUpload from './v-upload.vue';
import VDatePicker from './v-date-picker.vue';
import VEmojiPicker from '@directus/components/v-emoji-picker.vue';
import VWorkspace from '@directus/components/v-workspace.vue';
import VWorkspaceTile from '@directus/components/v-workspace-tile.vue';

export function registerComponents(app: App): void {
	app.component('VAvatar', VAvatar);
	app.component('VBadge', VBadge);
	app.component('VBreadcrumb', VBreadcrumb);
	app.component('VButton', VButton);
	app.component('VCardActions', VCardActions);
	app.component('VCardSubtitle', VCardSubtitle);
	app.component('VCardText', VCardText);
	app.component('VCardTitle', VCardTitle);
	app.component('VCard', VCard);
	app.component('VCheckbox', VCheckbox);
	app.component('VCheckboxTree', VCheckboxTree);
	app.component('VChip', VChip);
	app.component('VDetail', VDetail);
	app.component('VDialog', VDialog);
	app.component('VDivider', VDivider);
	app.component('VError', VError);
	app.component('VFancySelect', VFancySelect);
	app.component('VFieldTemplate', VFieldTemplate);
	app.component('VFieldList', VFieldList);
	app.component('VForm', VForm);
	app.component('VHover', VHover);
	app.component('VHighlight', VHighlight);
	app.component('VIcon', VIcon);
	app.component('VImage', VImage);
	app.component('VIconFile', VIconFile);
	app.component('VInfo', VInfo);
	app.component('VInput', VInput);
	app.component('VItemGroup', VItemGroup);
	app.component('VItem', VItem);
	app.component('VListGroup', VListGroup);
	app.component('VListItemContent', VListItemContent);
	app.component('VListItemHint', VListItemHint);
	app.component('VListItemIcon', VListItemIcon);
	app.component('VListItem', VListItem);
	app.component('VList', VList);
	app.component('VMenu', VMenu);
	app.component('VDrawer', VDrawer);
	app.component('VNotice', VNotice);
	app.component('VOverlay', VOverlay);
	app.component('VPagination', VPagination);
	app.component('VProgressCircular', VProgressCircular);
	app.component('VProgressLinear', VProgressLinear);
	app.component('VRadio', VRadio);
	app.component('VSelect', VSelect);
	app.component('VSheet', VSheet);
	app.component('VSkeletonLoader', VSkeletonLoader);
	app.component('VSlider', VSlider);
	app.component('VTabItem', VTabItem);
	app.component('VTab', VTab);
	app.component('VTable', VTable);
	app.component('VTabsItems', VTabsItems);
	app.component('VTabs', VTabs);
	app.component('VTemplateInput', VTemplateInput);
	app.component('VTextarea', VTextarea);
	app.component('VTextOverflow', VTextOverflow);
	app.component('VUpload', VUpload);
	app.component('VDatePicker', VDatePicker);
	app.component('VEmojiPicker', VEmojiPicker);
	app.component('VWorkspace', VWorkspace);
	app.component('VWorkspaceTile', VWorkspaceTile);

	app.component('TransitionBounce', TransitionBounce);
	app.component('TransitionDialog', TransitionDialog);
	app.component('TransitionExpand', TransitionExpand);

	app.component('RenderDisplay', RenderDisplay);
	app.component('RenderTemplate', RenderTemplate);
	app.component('ExportSidebarDetail', ExportSidebarDetail);
	app.component('SidebarDetail', SidebarDetail);
	app.component('UserPopover', UserPopover);
	app.component('ValueNull', ValueNull);
	app.component('DocsWrapper', DocsWrapper);
	app.component('DrawerItem', DrawerItem);
	app.component('DrawerBatch', DrawerBatch);
}
