import { randomUUID } from 'crypto';
import { License } from '@directus/license';
import type { DeepPartial } from '@directus/types';
import { generateKeyPair, type JWTPayload } from 'jose';
import { SignJWT } from 'jose/jwt/sign';
import { merge } from 'lodash-es';
import { DAY_IN_S } from './constants.js';
import type { MockLicense } from './types.js';

const ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

// random key based on this format: DXXXX-XXXXX-XXXXX-XXXXX-XXXXC
// where D is a constant
// where X is based on the alphabet
// where C is checksum of all Xes + D prefix generated by a luhnChecksum
function luhnChecksum(payload: string): string {
	let sum = 0;

	for (let i = 0; i < payload.length; i++) {
		const char = payload.at(-(1 + i)) as string;
		const value = ALPHABET.indexOf(char);
		const position = i + 1; // 1-indexed from the right of the payload

		if (position % 2 !== 0) {
			let doubled = value * 2;
			if (doubled >= 32) doubled -= 31;
			sum += doubled;
		} else {
			sum += value;
		}
	}

	const remainder = sum % 32;
	const expectedChecksumChar = ALPHABET[(32 - remainder) % 32] as string;

	return expectedChecksumChar;
}

export function generateKey() {
	const c = Array.from({ length: 23 }, () => Math.floor(Math.random() * ALPHABET.length))
		.map((i) => ALPHABET[i])
		.join('');

	return `D${c.slice(0, 4)}-${c.slice(4, 9)}-${c.slice(9, 14)}-${c.slice(14, 19)}-${c.slice(19, 23) + luhnChecksum(`D${c}`)}`;
}

export function createLicense(overrides?: DeepPartial<MockLicense>): MockLicense {
	const key = overrides?.key ?? generateKey();
	const now = Math.floor(Date.now() / 1000);

	return merge(
		{
			key,
			max_projects: 10,
			projects: [],
			addons: [],
			name: `mock-${key}`,
			meta: {
				name: 'mock',
				version: '2026-05-08',
				grace_period: DAY_IN_S,
				validation_interval: 60 * 60,
				expires_at: now + 30 * DAY_IN_S,
				offline: false,
			},
			entitlements: {
				collections: { limit: -1 },
				seats: { limit: -1 },
				activity_historical_timeframe: { limit: -1 },
				revision_historical_timeframe: { limit: -1 },
				sso_enabled: { default: true },
				offline_enabled: { default: false },
				telemetry_required: { default: false },
				display_powered_by: 'HIDDEN',
				custom_llms_enabled: { default: true },
				custom_permission_rules_enabled: { default: true },
				ai_translations_enabled: { default: true },
				production_enabled: { default: true },
				flows: { limit: -1 },
			},
		},
		overrides,
	);
}

const { privateKey, publicKey } = await generateKeyPair('EdDSA');

export { publicKey };

const TOKEN_LIFETIME_IN_S = 7 * 24 * 60 * 60;

export async function createToken(license: License) {
	const encodedToken = License.encode({ entitlements: license.entitlements, meta: license.meta });

	const now = Math.floor(Date.now() / 1000);

	return new SignJWT(encodedToken as JWTPayload)
		.setProtectedHeader({ alg: 'EdDSA' })
		.setIssuer('directus-licensing-service')
		.setAudience('directus')
		.setIssuedAt(now)
		.setJti(randomUUID())
		.setExpirationTime(now + TOKEN_LIFETIME_IN_S)
		.sign(privateKey);
}
