type: object
properties:
  id:
    description: Unique identifier for the setting.
    type: integer
    example: 1
  project_name:
    description: Name of the project, shown in the Data Studio.
    type: string
    example: Directus
  project_url:
    description: The url of the project. Link to the (public) website that goes with this project.
    type: string
    example: null
    nullable: true
  project_color:
    description: The brand color of the project.
    type: string
    format: hexcode
    example: null
    nullable: true
  project_logo:
    description: The logo of the project. Many-to-one to files.
    type: string
    example: null
    nullable: true
    oneOf:
      - $ref: files.yaml
  public_foreground:
    description: The foreground of the project. Many-to-one to files.
    type: string
    example: null
    nullable: true
    oneOf:
      - $ref: files.yaml
  public_background:
    description: The background of the project. Many-to-one to files.
    type: object
    example: null
    nullable: true
    oneOf:
      - $ref: files.yaml
  public_note:
    description: Note rendered on the public pages of the app.
    type: string
    example: null
    nullable: true
  auth_login_attempts:
    description: Allowed authentication login attempts before the user's status is set to blocked.
    type: integer
    example: 25
  auth_password_policy:
    description: Authentication password policy. What regex passwords must pass in order to be valid.
    type: string
    format: regex
    nullable: true
  storage_asset_transform:
    description: If the transform endpoints are allowed to be used on the assets endpoint. One of all, none or presets.
    type: string
    enum:
      - all
      - none
      - presets
    example: all
    nullable: true
  storage_asset_presets:
    description: What preset keys exist in the assets endpoint.
    type: array
    items:
      type: object
      properties:
        key:
          description: Key for the asset. Used in the assets endpoint.
          type: string
        fit:
          description: Whether to crop the thumbnail to match the size, or maintain the aspect ratio.
          type: string
          enum:
            - cover
            - contain
            - inside
            - outside
        width:
          description: Width of the thumbnail.
          type: integer
        height:
          description: Height of the thumbnail.
          type: integer
        withoutEnlargement:
          description: No image upscale
          type: boolean
        quality:
          description: Quality of the compression used.
          type: integer
        format:
          description: Reformat output image
          type: string
          enum:
            - jpeg
            - png
            - webp
            - tiff
            - avif
        transforms:
          description: Additional transformations to apply
          type: array
          nullable: true
          items:
            type: object
            properties:
              method:
                description: The Sharp method name
                type: string
              arguments:
                description: A list of arguments to pass to the Sharp method
                type: array
                nullable: true
                items:
                  type: object
                  properties:
                    argument:
                      description: A JSON representation of the argument value
                      type: string
    example: null
    nullable: true
  custom_css:
    description: CSS rules to override the App's default styling.
    nullable: true
    type: string
  storage_default_folder:
    description: Folder for uploaded files. Does not affect existing files.
    type: string
    format: uuid
  basemaps:
    description: Custom tiles to overriding the Mapbox defaults.
    type: array
    nullable: true
  mapbox_key:
    description: Mapbox Access Token.
    nullable: true
    type: string
  module_bar:
    description: What modules are enabled/added globally.
    type: array
    nullable: true
  project_descriptor:
    description: Descriptor of the project, shown in the Data Studio.
    nullable: true
    type: string
  custom_aspect_ratios:
    description: Custom aspect ratios in the image editor.
    type: array
    nullable: true
  public_favicon:
    nullable: true
    description: Favicon for the Data Studio. Many-to-one to files.
    type: string
    oneOf:
      - $ref: files.yaml
  default_appearance:
    description: One of auto, light, dark.
    nullable: false
    type: string
    enum:
      - auto
      - light
      - dark
  default_theme_light:
    description: Default theme to use in light mode.
    nullable: true
    type: string
  theme_light_overrides:
    description: Default customization for light theme in use.
    type: object
    nullable: true
  default_theme_dark:
    description: Default theme to use in dark mode.
    nullable: true
    type: string
  theme_dark_overrides:
    description: Default customization for dark theme in use.
    type: object
    nullable: true
  report_error_url:
    description: |
      Link to the error report page. This is a template URL that has access to the following object

      ```
        {
          error: {
            name?: string;
            message?: string;
          };
          route: {
            fullPath: string;
            hash: string;
            name: string;
            path: string;
            query: string;
          };
          navigator: {
            language: string;
            userAgent: string;
          };
          user: {
            id?: string | number;
            first_name?: string;
            last_name?: string;
            title?: string;
            description?: string;
            location?: string;
            status?: string;
          };
          role: {
            id?: string;
            name?: string;
          };
        }
      ```
    nullable: true
    type: string
  report_bug_url:
    description: Link to the bug report page.
    nullable: true
    type: string
  report_feature_url:
    description: Link to the feature request page.
    nullable: true
    type: string
x-collection: directus_settings
