summary: Get OpenAPI Specification
description: Retrieve the OpenAPI spec for the current project.
operationId: readOpenApiSpec
responses:
  '200':
    description: Successful request
    content:
      application/json:
        schema:
          type: object
          description: Object conforming to the OpenAPI Specification
  '401':
    $ref: ../../../../components/responses.yaml#/UnauthorizedError
  '404':
    $ref: ../../../../components/responses.yaml#/NotFoundError
security: []
tags:
- Server
x-codeSamples:
- label: Directus SDK
  lang: JavaScript
  source: |
    import { createDirectus, rest, readOpenApiSpec } from '@directus/sdk';

    const client = createDirectus('directus_project_url').with(rest());

    const result = await client.request(readOpenApiSpec());
- label: GraphQL
  lang: GraphQL
  source: |
    POST /graphql/system

    type Query {
      server_specs_oas: String
    }
