#!/usr/bin/env bash
#
# Worktree Setup Script for f2f-directus
# Called by git-worktree-runner after creating a new worktree
#
# Usage: ./scripts/gtr-setup.sh [--services postgres,redis,minio] [--skip-bootstrap]
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Default services (just postgres)
SERVICES="postgres"
SKIP_BOOTSTRAP=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --services)
            SERVICES="$2"
            shift 2
            ;;
        --skip-bootstrap)
            SKIP_BOOTSTRAP=true
            shift
            ;;
        *)
            shift
            ;;
    esac
done

# Calculate unique port offset based on directory path hash (0-99)
# This ensures each worktree gets unique ports
calculate_port_offset() {
    local hash=$(echo "$PROJECT_DIR" | md5sum | tr -d -c '0-9' | cut -c1-4)
    echo $((10#$hash % 100 * 100))
}

PORT_OFFSET=$(calculate_port_offset)

# Base ports from docker-compose.yml
declare -A BASE_PORTS=(
    [postgres]=5100
    [postgres10]=5111
    [mysql]=5101
    [mysql5]=5108
    [maria]=5102
    [mssql]=5103
    [oracle]=5104
    [cockroachdb]=5113
    [redis]=5105
    [minio]=5106
    [minio_admin]=5112
    [azure]=5107
    [keycloak]=5110
    [maildev_smtp]=1025
    [maildev_web]=1080
    [otel_grpc]=4317
    [otel_http]=4318
    [otel_metrics]=8888
    [tempo]=3200
    [loki]=3100
    [prometheus]=9090
    [grafana]=3000
)

# Calculate actual ports for this worktree
get_port() {
    local service=$1
    local base=${BASE_PORTS[$service]}
    echo $((base + PORT_OFFSET))
}

echo "═══════════════════════════════════════════════════════════════"
echo "  f2f-directus Worktree Setup"
echo "═══════════════════════════════════════════════════════════════"
echo "  Directory:    $PROJECT_DIR"
echo "  Port offset:  +$PORT_OFFSET"
echo "  Services:     $SERVICES"
echo "═══════════════════════════════════════════════════════════════"

# Generate docker-compose.override.yml with unique ports
echo "→ Generating docker-compose.override.yml..."
cat > "$PROJECT_DIR/docker-compose.override.yml" << EOF
# Auto-generated by gtr-setup.sh - DO NOT EDIT
# Port offset: $PORT_OFFSET (based on worktree path hash)

services:
  postgres:
    ports:
      - $(get_port postgres):5432

  postgres10:
    ports:
      - $(get_port postgres10):5432

  mysql:
    ports:
      - $(get_port mysql):3306

  mysql5:
    ports:
      - $(get_port mysql5):3306

  maria:
    ports:
      - $(get_port maria):3306

  mssql:
    ports:
      - $(get_port mssql):1433

  oracle:
    ports:
      - $(get_port oracle):1521

  cockroachdb:
    ports:
      - $(get_port cockroachdb):26257

  redis:
    ports:
      - $(get_port redis):6379

  minio:
    ports:
      - $(get_port minio):9000
      - $(get_port minio_admin):9001

  azure:
    ports:
      - $(get_port azure):10000

  keycloak:
    ports:
      - $(get_port keycloak):8080

  maildev:
    ports:
      - $(get_port maildev_smtp):1025
      - $(get_port maildev_web):1080

  otel-collector:
    ports:
      - $(get_port otel_grpc):4317
      - $(get_port otel_http):4318
      - $(get_port otel_metrics):8888

  tempo:
    ports:
      - $(get_port tempo):3200

  loki:
    ports:
      - $(get_port loki):3100

  prometheus:
    ports:
      - $(get_port prometheus):9090

  grafana:
    ports:
      - $(get_port grafana):3000
EOF

# Generate api/.env
echo "→ Generating api/.env..."
cat > "$PROJECT_DIR/api/.env" << EOF
# Auto-generated by gtr-setup.sh
# Port offset: $PORT_OFFSET

DB_CLIENT=postgres
DB_HOST=localhost
DB_PORT=$(get_port postgres)
DB_DATABASE=directus
DB_USER=postgres
DB_PASSWORD=secret

ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=directus
SECRET=$(openssl rand -hex 32)
PUBLIC_URL=http://localhost:8055

# OpenTelemetry Configuration
OPENTELEMETRY_ENABLED=true
OPENTELEMETRY_SERVICE_NAME=directus-api
OPENTELEMETRY_EXPORTER_OTLP_ENDPOINT=http://localhost:$(get_port otel_http)
EOF

# Install dependencies
echo "→ Installing dependencies..."
cd "$PROJECT_DIR"
pnpm install

# Build
echo "→ Building packages..."
pnpm build

# Start docker services
echo "→ Starting docker services: $SERVICES..."
docker compose up -d ${SERVICES//,/ }

# Wait for postgres to be ready
if [[ "$SERVICES" == *"postgres"* ]]; then
    echo "→ Waiting for postgres to be ready..."
    POSTGRES_PORT=$(get_port postgres)
    for i in {1..30}; do
        if docker compose exec -T postgres pg_isready -U postgres > /dev/null 2>&1; then
            echo "  Postgres is ready!"
            break
        fi
        echo "  Waiting... ($i/30)"
        sleep 1
    done
fi

# Bootstrap directus
if [ "$SKIP_BOOTSTRAP" = false ]; then
    echo "→ Bootstrapping Directus..."
    cd "$PROJECT_DIR/api"
    pnpm cli bootstrap
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  Setup complete!"
echo "═══════════════════════════════════════════════════════════════"
echo "  Postgres port: $(get_port postgres)"
echo "  API .env:      $PROJECT_DIR/api/.env"
echo ""
echo "  To start the API:  cd api && pnpm dev"
echo "  To start the App:  cd app && pnpm dev"
echo ""
echo "  To manage services:"
echo "    docker compose up -d postgres redis    # Start specific services"
echo "    docker compose down                    # Stop all services"
echo "═══════════════════════════════════════════════════════════════"
