#!/usr/bin/env bash
#
# Worktree Setup Script for f2f-directus
# Called by git-worktree-runner after creating a new worktree
#
# Usage: ./scripts/gtr-setup.sh [--services postgres,redis,minio] [--skip-bootstrap]
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Default services (just postgres)
SERVICES="postgres"
SKIP_BOOTSTRAP=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --services)
            SERVICES="$2"
            shift 2
            ;;
        --skip-bootstrap)
            SKIP_BOOTSTRAP=true
            shift
            ;;
        *)
            shift
            ;;
    esac
done

# Calculate unique port offset based on directory path hash (0-99)
# This ensures each worktree gets unique ports
calculate_port_offset() {
    local hash=$(echo "$PROJECT_DIR" | md5sum | tr -d -c '0-9' | cut -c1-4)
    echo $((10#$hash % 100 * 100))
}

PORT_OFFSET=$(calculate_port_offset)

# Base ports from docker-compose.yml
declare -A BASE_PORTS=(
    [postgres]=5100
    [postgres10]=5111
    [mysql]=5101
    [mysql5]=5108
    [maria]=5102
    [mssql]=5103
    [oracle]=5104
    [cockroachdb]=5113
    [redis]=5105
    [minio]=5106
    [minio_admin]=5112
    [azure]=5107
    [keycloak]=5110
    [maildev_smtp]=1025
    [maildev_web]=1080
    [otel_grpc]=4317
    [otel_http]=4318
    [otel_metrics]=8888
    [tempo]=3200
    [loki]=3100
    [prometheus]=9090
    [grafana]=3000
)

# Calculate actual ports for this worktree
get_port() {
    local service=$1
    local base=${BASE_PORTS[$service]}
    echo $((base + PORT_OFFSET))
}

echo "═══════════════════════════════════════════════════════════════"
echo "  f2f-directus Worktree Setup"
echo "═══════════════════════════════════════════════════════════════"
echo "  Directory:    $PROJECT_DIR"
echo "  Port offset:  +$PORT_OFFSET"
echo "  Services:     $SERVICES"
echo "═══════════════════════════════════════════════════════════════"

# Copy environment files from main repo (REPO_ROOT is set by gtr)
if [ -n "$REPO_ROOT" ] && [ "$REPO_ROOT" != "$PROJECT_DIR" ]; then
    echo "→ Copying environment files from main repo..."

    # Copy observability env file if it exists
    if [ -f "$REPO_ROOT/observability/configs/.env.observability" ]; then
        mkdir -p "$PROJECT_DIR/observability/configs"
        cp "$REPO_ROOT/observability/configs/.env.observability" "$PROJECT_DIR/observability/configs/"
    fi

    # Copy any root .env files
    for envfile in "$REPO_ROOT"/.env "$REPO_ROOT"/.env.local; do
        if [ -f "$envfile" ]; then
            cp "$envfile" "$PROJECT_DIR/"
        fi
    done
fi

# Generate .env file with port variables for docker-compose
echo "→ Generating .env with port configuration..."
cat > "$PROJECT_DIR/.env" << EOF
# Auto-generated by gtr-setup.sh - DO NOT EDIT
# Port offset: $PORT_OFFSET (based on worktree path hash)

# Database ports
POSTGRES_PORT=$(get_port postgres)
POSTGRES10_PORT=$(get_port postgres10)
MYSQL_PORT=$(get_port mysql)
MYSQL5_PORT=$(get_port mysql5)
MARIA_PORT=$(get_port maria)
MSSQL_PORT=$(get_port mssql)
ORACLE_PORT=$(get_port oracle)
COCKROACHDB_PORT=$(get_port cockroachdb)

# Service ports
REDIS_PORT=$(get_port redis)
MINIO_PORT=$(get_port minio)
MINIO_ADMIN_PORT=$(get_port minio_admin)
AZURE_PORT=$(get_port azure)
KEYCLOAK_PORT=$(get_port keycloak)
MAILDEV_SMTP_PORT=$(get_port maildev_smtp)
MAILDEV_WEB_PORT=$(get_port maildev_web)

# OpenTelemetry ports
OTEL_GRPC_PORT=$(get_port otel_grpc)
OTEL_HTTP_PORT=$(get_port otel_http)
OTEL_METRICS_PORT=$(get_port otel_metrics)
TEMPO_PORT=$(get_port tempo)
LOKI_PORT=$(get_port loki)
PROMETHEUS_PORT=$(get_port prometheus)
GRAFANA_PORT=$(get_port grafana)
EOF

# Generate api/.env
echo "→ Generating api/.env..."
cat > "$PROJECT_DIR/api/.env" << EOF
# Auto-generated by gtr-setup.sh
# Port offset: $PORT_OFFSET

DB_CLIENT=postgres
DB_HOST=localhost
DB_PORT=$(get_port postgres)
DB_DATABASE=directus
DB_USER=postgres
DB_PASSWORD=secret

ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=directus
SECRET=$(openssl rand -hex 32)
PUBLIC_URL=http://localhost:8055

# OpenTelemetry Configuration
OPENTELEMETRY_ENABLED=true
OPENTELEMETRY_SERVICE_NAME=directus-api
OPENTELEMETRY_EXPORTER_OTLP_ENDPOINT=http://localhost:$(get_port otel_http)
EOF

# Install dependencies
echo "→ Installing dependencies..."
cd "$PROJECT_DIR"
pnpm install

# Build
echo "→ Building packages..."
pnpm build

# Start docker services
echo "→ Starting docker services: $SERVICES..."
docker compose up -d ${SERVICES//,/ }

# Wait for postgres to be ready
if [[ "$SERVICES" == *"postgres"* ]]; then
    echo "→ Waiting for postgres to be ready..."
    POSTGRES_PORT=$(get_port postgres)
    for i in {1..30}; do
        if docker compose exec -T postgres pg_isready -U postgres > /dev/null 2>&1; then
            echo "  Postgres is ready!"
            break
        fi
        echo "  Waiting... ($i/30)"
        sleep 1
    done
fi

# Bootstrap directus
if [ "$SKIP_BOOTSTRAP" = false ]; then
    echo "→ Bootstrapping Directus..."
    cd "$PROJECT_DIR/api"
    pnpm cli bootstrap
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  Setup complete!"
echo "═══════════════════════════════════════════════════════════════"
echo "  Postgres port: $(get_port postgres)"
echo "  API .env:      $PROJECT_DIR/api/.env"
echo ""
echo "  To start the API:  cd api && pnpm dev"
echo "  To start the App:  cd app && pnpm dev"
echo ""
echo "  To manage services:"
echo "    docker compose up -d postgres redis    # Start specific services"
echo "    docker compose down                    # Stop all services"
echo "═══════════════════════════════════════════════════════════════"
