const PANEL_WIDTH = 14
const PANEL_HEIGHT = 14
const ATTACHMENT_OFFSET = {x: - 2, y: 3 * 20}
const RESOLVE_OFFSET = {x: 10 * 20, y: PANEL_WIDTH * 20 - 2}
const REJECT_OFFSET = {x: 12 * 20, y: PANEL_WIDTH * 20 - 2}
export {PANEL_HEIGHT, PANEL_WIDTH, ATTACHMENT_OFFSET, RESOLVE_OFFSET, REJECT_OFFSET}