name: Prepare
description: Install dependencies and build the platform
inputs:
  build:
    description: Build the production bundle of the platform
    required: false
    default: "true"
  registry:
    description: NPM registry to set up for auth
    required: false
  package-filter:
    description: Ignore certain packages from being built when build is true
    required: false
    default: "!docs"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        registry-url: ${{ inputs.registry }}
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Build
      if: inputs.build == 'true'
      shell: bash
      env:
        npm_config_workspace_concurrency: 1
        NODE_OPTIONS: --max_old_space_size=6144
      run: pnpm --recursive --filter '${{ inputs.package-filter }}' run build
