name: Prepare
description: Install dependencies and build the platform
inputs:
  build:
    description: Build the production bundle of the platform
    required: false
    default: 'true'
  registry:
    description: NPM registry to set up for auth
    required: false

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        registry-url: ${{ inputs.registry }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45

    - name: Build
      if: inputs.build == 'true'
      shell: bash
      env:
        npm_config_workspace_concurrency: 1
        NODE_OPTIONS: --max_old_space_size=6144
      run: pnpm run build
