import InterfaceWYSIWYG from './wysiwyg.vue';
import { defineInterface } from '@/interfaces/define';

export default defineInterface(({ i18n }) => ({
	id: 'wysiwyg',
	name: i18n.t('wysiwyg'),
	icon: 'format_quote',
	component: InterfaceWYSIWYG,
	options: [
		{
			field: 'toolbar',
			name: i18n.t('toolbar'),
			width: 'full',
			interface: 'checkboxes',
			default_value: [
				'bold',
				'italic',
				'underline',
				'removeformat',
				'link',
				'bullist',
				'numlist',
				'blockquote',
				'h1',
				'h2',
				'h3',
				'image',
				'media',
				'hr',
				'code',
				'fullscreen',
			],
			options: {
				choices: {
					aligncenter: i18n.t('wysiwyg_options.aligncenter'),
					alignjustify: i18n.t('wysiwyg_options.alignjustify'),
					alignleft: i18n.t('wysiwyg_options.alignleft'),
					alignnone: i18n.t('wysiwyg_options.alignnone'),
					alignright: i18n.t('wysiwyg_options.alignright'),
					forecolor: i18n.t('wysiwyg_options.forecolor'),
					backcolor: i18n.t('wysiwyg_options.backcolor'),
					bold: i18n.t('wysiwyg_options.bold'),
					italic: i18n.t('wysiwyg_options.italic'),
					underline: i18n.t('wysiwyg_options.underline'),
					strikethrough: i18n.t('wysiwyg_options.strikethrough'),
					subscript: i18n.t('wysiwyg_options.subscript'),
					superscript: i18n.t('wysiwyg_options.superscript'),
					blockquote: i18n.t('wysiwyg_options.blockquote'),
					bullist: i18n.t('wysiwyg_options.bullist'),
					numlist: i18n.t('wysiwyg_options.numlist'),
					hr: i18n.t('wysiwyg_options.hr'),
					link: i18n.t('wysiwyg_options.link'),
					unlink: i18n.t('wysiwyg_options.unlink'),
					media: i18n.t('wysiwyg_options.media'),
					image: i18n.t('wysiwyg_options.image'),
					copy: i18n.t('wysiwyg_options.copy'),
					cut: i18n.t('wysiwyg_options.cut'),
					paste: i18n.t('wysiwyg_options.paste'),
					h1: i18n.t('wysiwyg_options.h1'),
					h2: i18n.t('wysiwyg_options.h2'),
					h3: i18n.t('wysiwyg_options.h3'),
					h4: i18n.t('wysiwyg_options.h4'),
					h5: i18n.t('wysiwyg_options.h5'),
					h6: i18n.t('wysiwyg_options.h6'),
					fontselect: i18n.t('wysiwyg_options.fontselect'),
					fontsizeselect: i18n.t('wysiwyg_options.fontsizeselect'),
					indent: i18n.t('wysiwyg_options.indent'),
					outdent: i18n.t('wysiwyg_options.outdent'),
					undo: i18n.t('wysiwyg_options.undo'),
					redo: i18n.t('wysiwyg_options.redo'),
					remove: i18n.t('wysiwyg_options.remove'),
					removeformat: i18n.t('wysiwyg_options.removeformat'),
					selectall: i18n.t('wysiwyg_options.selectall'),
					table: i18n.t('wysiwyg_options.table'),
					visualaid: i18n.t('wysiwyg_options.visualaid'),
					code: i18n.t('wysiwyg_options.code'),
					fullscreen: i18n.t('wysiwyg_options.fullscreen'),
					'ltr rtl': i18n.t('wysiwyg_options.directionality'),
				},
			},
		},
		{
			field: 'font',
			name: i18n.t('font'),
			width: 'half',
			interface: 'dropdown',
			default_value: 'serif',
			options: {
				items: [
					{ itemText: i18n.t('sans_serif'), itemValue: 'sans-serif' },
					{ itemText: i18n.t('monospace'), itemValue: 'monospace' },
					{ itemText: i18n.t('serif'), itemValue: 'serif' },
				],
			},
		},
		{
			field: 'customFormats',
			name: i18n.t('custom_formats'),
			interface: 'code',
			options: {
				type: 'application/json',
				template: {
					title: 'My Custom Format',
					inline: 'span',
					classes: 'custom-wrapper',
					styles: { color: '#00ff00', 'font-size': '20px' },
					attributes: { title: 'My Custom Wrapper' },
				},
			},
		},
		{
			field: 'tinymceOverrides',
			name: i18n.t('tinymce_options_override'),
			interface: 'code',
			options: {
				type: 'application/json',
			},
		},
	],
}));
