name: DirectApp CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  PNPM_VERSION: '8'
  DIRECTUS_VERSION: '11.12.0'

jobs:
  # ========================================
  # Lint and Type Check
  # ========================================
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: 'extensions/pnpm-lock.yaml'

      - name: Install extension dependencies
        working-directory: ./extensions
        run: pnpm install --frozen-lockfile

      - name: Run type check
        working-directory: ./extensions
        run: pnpm type-check

      - name: Run linter
        working-directory: ./extensions
        run: pnpm lint || echo "Linting completed with warnings"

  # ========================================
  # Build Extensions
  # ========================================
  build-extensions:
    name: Build Extensions
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: 'extensions/pnpm-lock.yaml'

      - name: Install dependencies
        working-directory: ./extensions
        run: pnpm install --frozen-lockfile

      - name: Build all extensions
        working-directory: ./extensions
        run: pnpm build

      - name: Upload extension artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extensions-dist
          path: extensions/*/dist
          retention-days: 7

  # ========================================
  # Schema Validation
  # ========================================
  validate-schema:
    name: Validate Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run permission linter
        run: |
          chmod +x schema/scripts/lint-permissions.sh
          ./schema/scripts/lint-permissions.sh prod

      - name: Validate schema snapshots exist
        run: |
          if [ ! -f "schema/snapshots/prod.json" ]; then
            echo "❌ Production schema snapshot not found"
            exit 1
          fi
          echo "✅ Production schema snapshot found"

      - name: Check for schema drift
        if: github.event_name == 'pull_request'
        run: |
          echo "Checking for unexpected schema changes..."
          # This would compare PR schema against main
          # For now, just validate the snapshot is valid JSON
          jq empty schema/snapshots/prod.json
          echo "✅ Schema snapshot is valid JSON"

  # ========================================
  # Integration Tests with Ephemeral Directus
  # ========================================
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [build-extensions]

    services:
      postgres:
        image: postgres:15.6
        env:
          POSTGRES_DB: directus_test
          POSTGRES_USER: directus
          POSTGRES_PASSWORD: test_password
          POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7.2.4-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download extension artifacts
        uses: actions/download-artifact@v4
        with:
          name: extensions-dist
          path: extensions/

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Directus CLI
        run: npm install -g directus@${{ env.DIRECTUS_VERSION }}

      - name: Create test environment file
        run: |
          cat > .env.test << EOF
          KEY=$(openssl rand -base64 32)
          SECRET=$(openssl rand -base64 64)

          DB_CLIENT=pg
          DB_HOST=localhost
          DB_PORT=5432
          DB_DATABASE=directus_test
          DB_USER=directus
          DB_PASSWORD=test_password

          CACHE_ENABLED=true
          CACHE_STORE=redis
          REDIS=redis://localhost:6379

          ADMIN_EMAIL=admin@test.local
          ADMIN_PASSWORD=TestPassword123!

          PUBLIC_URL=http://localhost:8055

          LOG_LEVEL=error
          TELEMETRY=false

          EXTENSIONS_PATH=./extensions
          EOF

      - name: Start ephemeral Directus instance
        run: |
          npx directus bootstrap
          npx directus start &
          echo $! > directus.pid

          # Wait for Directus to be ready
          timeout 60 bash -c 'until curl -sf http://localhost:8055/server/health; do sleep 2; done'
        env:
          ENV_FILE_PATH: .env.test

      - name: Apply schema snapshot
        run: |
          npx directus schema apply schema/snapshots/prod.json --yes

      - name: Test vehicle lookup endpoint
        run: |
          # Health check
          curl -sf http://localhost:8055/vehicle-lookup/health | jq .

          # Test without token (should fail gracefully)
          curl -sf http://localhost:8055/vehicle-lookup/regnr/TEST123 || echo "Expected error (no API token)"

      - name: Test workflow guard hook
        run: |
          # This would need a proper test suite
          # For now, just verify Directus started with extensions
          curl -sf http://localhost:8055/server/info | jq .
          echo "✅ Directus running with extensions"

      - name: Stop Directus
        if: always()
        run: |
          if [ -f directus.pid ]; then
            kill $(cat directus.pid) || true
          fi

  # ========================================
  # Security Scan
  # ========================================
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Check for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

  # ========================================
  # Build Docker Image (on main branch)
  # ========================================
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [build-extensions, validate-schema, integration-test]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ========================================
  # Deploy to Dokploy (manual trigger only)
  # ========================================
  deploy-dokploy:
    name: Deploy to Dokploy
    runs-on: ubuntu-latest
    needs: [build-image]
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via Dokploy webhook
        run: |
          curl -X POST "${{ secrets.DOKPLOY_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{"ref": "refs/heads/main"}'

      - name: Wait for deployment
        run: |
          echo "Waiting 60 seconds for deployment..."
          sleep 60

      - name: Health check
        run: |
          curl -sf "${{ secrets.DIRECTUS_URL }}/server/health" || exit 1
          echo "✅ Deployment successful"

  # ========================================
  # Summary Report
  # ========================================
  report:
    name: CI/CD Summary
    runs-on: ubuntu-latest
    needs: [lint, build-extensions, validate-schema, integration-test, security-scan]
    if: always()

    steps:
      - name: Generate summary
        run: |
          echo "# DirectApp CI/CD Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Check | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Lint & Type Check | ${{ needs.lint.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Build Extensions | ${{ needs.build-extensions.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Validate Schema | ${{ needs.validate-schema.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Integration Tests | ${{ needs.integration-test.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Security Scan | ${{ needs.security-scan.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
