name: Blackbox Tests

on:
  push:
    branches:
      - main
    paths:
      - api/**
      - tests/**
      - packages/**
      - package.json
      - pnpm-lock.yaml
      - .github/workflows/blackbox.yml
  workflow_call:

concurrency:
  group: loadtests-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max_old_space_size=6144

jobs:
  loadtests:
    name: ${{ matrix.vendor }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        vendor:
          - sqlite3
          - postgres
          - mysql
          - maria
          - mssql
          - cockroachdb
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run tests
        run: pnpm run test:load --wait 5 --platform ${{ matrix.vendor }} version
