import { Field } from '@directus/types';
import { useI18n } from 'vue-i18n';

export const useProjectFields = function (): Field[] {
	const { t } = useI18n();
	return [
		{
			collection: 'onboarding',
			name: t('fields.directus_settings.project_name'),
			field: 'project_name',
			type: 'string',
			schema: {
				name: 'project_name',
				table: 'onboarding',
				schema: 'public',
				data_type: 'character varying',
				is_nullable: false,
				generation_expression: null,
				default_value: null,
				is_generated: false,
				max_length: 255,
				comment: null,
				numeric_precision: null,
				numeric_scale: null,
				is_unique: false,
				is_primary_key: false,
				has_auto_increment: false,
				foreign_key_schema: null,
				foreign_key_table: null,
				foreign_key_column: null,
			},
			meta: {
				id: 27,
				collection: 'onboarding',
				field: 'project_name',
				special: null,
				interface: 'input',
				options: { placeholder: t('fields.directus_settings.project_name'), trim: true },
				display: null,
				display_options: null,
				readonly: false,
				hidden: false,
				sort: 8,
				width: 'half',
				translations: null,
				note: null,
				conditions: null,
				required: false,
				group: null,
				validation: null,
				validation_message: null,
			},
		},
		{
			collection: 'onboarding',
			name: t('fields.directus_settings.project_url'),
			field: 'project_url',
			type: 'string',
			schema: {
				name: 'project_url',
				table: 'onboarding',
				schema: 'public',
				data_type: 'character varying',
				is_nullable: false,
				generation_expression: null,
				default_value: null,
				is_generated: false,
				max_length: 255,
				comment: null,
				numeric_precision: null,
				numeric_scale: null,
				is_unique: false,
				is_primary_key: false,
				has_auto_increment: false,
				foreign_key_schema: null,
				foreign_key_table: null,
				foreign_key_column: null,
			},
			meta: {
				id: 28,
				collection: 'onboarding',
				field: 'project_url',
				special: null,
				interface: 'input',
				options: { placeholder: t('fields.directus_settings.project_url'), trim: true },
				display: null,
				display_options: null,
				readonly: false,
				hidden: false,
				sort: 9,
				width: 'half',
				translations: null,
				note: null,
				conditions: null,
				required: false,
				group: null,
				validation: null,
				validation_message: null,
			},
		},
		{
			collection: 'onboarding',
			name: t('fields.directus_settings.project_color'),
			field: 'project_color',
			type: 'string',
			schema: {
				name: 'project_color',
				table: 'onboarding',
				schema: 'public',
				data_type: 'character varying',
				is_nullable: false,
				generation_expression: null,
				default_value: null,
				is_generated: false,
				max_length: 255,
				comment: null,
				numeric_precision: null,
				numeric_scale: null,
				is_unique: false,
				is_primary_key: false,
				has_auto_increment: false,
				foreign_key_schema: null,
				foreign_key_table: null,
				foreign_key_column: null,
			},
			meta: {
				id: 29,
				collection: 'onboarding',
				field: 'project_color',
				special: null,
				interface: 'select-color',
				options: { placeholder: t('fields.directus_settings.project_color'), trim: true },
				display: null,
				display_options: null,
				readonly: false,
				hidden: false,
				sort: 11,
				width: 'half',
				translations: null,
				note: null,
				conditions: null,
				required: false,
				group: null,
				validation: null,
				validation_message: null,
			},
		},
		{
			collection: 'onboarding',
			name: t('fields.directus_settings.project_logo'),
			field: 'project_logo',
			type: 'uuid',
			schema: {
				name: 'project_logo',
				table: 'onboarding',
				schema: 'public',
				data_type: 'uuid',
				is_nullable: true,
				generation_expression: null,
				default_value: null,
				is_generated: false,
				max_length: null,
				comment: null,
				numeric_precision: null,
				numeric_scale: null,
				is_unique: false,
				is_primary_key: false,
				has_auto_increment: false,
				foreign_key_schema: 'public',
				foreign_key_table: 'directus_files',
				foreign_key_column: 'id',
			},
			meta: {
				id: 30,
				collection: 'onboarding',
				field: 'project_logo',
				special: ['file'],
				interface: 'file-image',
				options: { crop: false },
				display: null,
				display_options: null,
				readonly: false,
				hidden: false,
				sort: 10,
				width: 'half',
				translations: null,
				note: null,
				conditions: null,
				required: false,
				group: null,
				validation: null,
				validation_message: null,
			},
		},
		{
			collection: 'onboarding',
			name: t('onboarding.project.use_case'),
			field: 'project_use_case',
			type: 'string',
			schema: {
				name: 'project_use_case',
				table: 'onboarding',
				schema: 'public',
				data_type: 'character varying',
				is_nullable: true,
				generation_expression: null,
				default_value: null,
				is_generated: false,
				max_length: 255,
				comment: null,
				numeric_precision: null,
				numeric_scale: null,
				is_unique: false,
				is_primary_key: false,
				has_auto_increment: false,
				foreign_key_schema: null,
				foreign_key_table: null,
				foreign_key_column: null,
			},
			meta: {
				id: 31,
				collection: 'onboarding',
				field: 'project_use_case',
				special: null,
				interface: 'select-radio',
				options: {
					choices: [
						{ text: t('onboarding.project.personal'), value: 'personal' },
						{ text: t('onboarding.project.work'), value: 'work' },
						{ text: t('onboarding.project.exploring'), value: 'exploring' },
					],
				},
				display: null,
				display_options: null,
				readonly: false,
				hidden: false,
				sort: 12,
				width: 'full',
				translations: null,
				note: null,
				conditions: null,
				required: false,
				group: null,
				validation: null,
				validation_message: null,
			},
		},
	];
};
